### ISSUE TITLE
Problem with "Autopause if tab loses focus"

### ISSUE THREAD

**Issue by zkisaboss** [raingart/Nova-YouTube-extension#100]
1.43.4 | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

Autopause only works when switching between fullscreen windows.
YouTube video doesn't pause when switching between applications or tabs in the same window.

**Comment by zkisaboss** [comment]
Also, I wanted to thank you for building such a fantastic script/extension. I respect your programming skills 🤜

**Comment by raingart** [comment]
try replacing this line:
```
if (document.visibilityState == 'hidden' && 'PLAYING' == NOVA.getPlayerState()) {
```
on
```
if ('PLAYING' == NOVA.getPlayerState()) {
```

Probably the reason is that `document.visibilityState` update after`window.blur` event

**Comment by raingart** [comment]
i replaced the line in this version
https://openuserjs.org/scripts/raingart/Nova_YouTube

**Comment by zkisaboss** [comment]
I'm actually using the extension since it has better latency.
I'll test the Userscript w/ that change and if it works I'll stick with that until the extension gets an update.

**Comment by zkisaboss** [comment]
The fix works, but minor bug when switching quickly between tabs with 'autoplay on focus' enabled. Likely timing issue with code execution.

**Comment by Eisys** [comment]
Hey @raingart, sorry to message on a closed issue but reading this made me curious.

Does running Nova as an extension actually improve it's latency/loading speed compared to userscript?

In my case it would be in Chrome as an unpacked extension.

**Comment by Eisys** [comment]
Thank you for the insight. I will keep using userscript.

👍

**Comment by zkisaboss** [comment]
I'm curious about execution latency vs the code being run. Becuase it just appeared like extensions cleaned up the page UI faster.
