### ISSUE TITLE
Minor Conflict with Autoplay and Autopause

### ISSUE THREAD

**Issue by zkisaboss** [raingart/Nova-YouTube-extension#101]
0.43.4 | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

Autopause should take precedence over autoplay for faster video pausing, which will prevent conflicts with autoplay.

**Comment by raingart** [comment]
Yes, there are conflicts. Separate functions work. But together they overlap each other's functions. The error is that the functions display the plugin parameters. But in reality, there should be a drop-down list with a list of the current mode of operation.

**Comment by zkisaboss** [comment]
Is this issue fixable?

**Comment by raingart** [comment]
maybe yes (I do not remember). try to check
https://gist.github.com/raingart/12695858bd13e356ac87350edf651193
