### ISSUE TITLE
Control panel below the player

### ISSUE THREAD

**Issue by MarkSpizu** [raingart/Nova-YouTube-extension#102]
"Control panel below the player" ON not working with videos from watch later for example.

Once the video is loading the player buttons disappear. Click to pause and you can only see a small progress bar.

<a href="https://www.imagebam.com/view/MENVLSE" target="_blank"><img src="https://images4.imagebam.com/ce/83/c6/MENVLSE_o.png" alt="Screenshot 2023-08-22 at 12-38-39 Happy Tree Friends Marathon (Part 3).png"/></a>

**Comment by MarkSpizu** [comment]
The videos from personal playlists don't work with "Control panel below the player" ON.

If "Control panel below the player" is OFF everything works fine. 

Script latest. Firefox latest, Violentmonkey 2.13.3.

**Comment by MarkSpizu** [comment]
https://www.youtube.com/playlist?list=PLD954AD90548599FE

**Comment by MarkSpizu** [comment]
Tested with latest Chrome and same playlists don't work with "Control panel below the player" ON.

**Comment by raingart** [comment]
![Screenshot_5](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/1c74581c-8856-40ea-a000-8a3e7fbdcc4f)

![Screenshot_6](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/3c3e5321-b9cb-4f1a-96a6-997e8b9b0743)

**Comment by MarkSpizu** [comment]
Once I sign out it works. Maybe my account is probably in some beta test. Thanks for everything!

**Comment by MarkSpizu** [comment]
I just noticed (in your screenshots) that your player has straight corners. See my screenshot my player has little round corners (I never seen that before). So it is clear that my account is under beta test. Thanks!

**Comment by MarkSpizu** [comment]
This script fixed my bug

https://greasyfork.org/en/scripts/453802-youtube-non-rounded-design

**Comment by raingart** [comment]
the script you specified uses a lot of experimental flags. I think one of them cancels the new functionality.

Nova has a similar plugin called "Square avatars". But it cancels rounding through css, which is safer than flags

**Comment by MarkSpizu** [comment]
"Square avatars" it has no effect. After full screen/Exit full screen the player buttons disappear (as in my first screenshot).

With that script the player buttons are kept. 

<a href="https://www.imagebam.com/view/MENVSUN" target="_blank"><img src="https://images4.imagebam.com/dd/ed/45/MENVSUN_o.png" alt="Screenshot 2023-08-22 at 17-28-34 Happy Tree Friends Marathon (Part 3).png"/></a>

**Comment by raingart** [comment]
In a neighboring issue, one user mentioned that a rounded player happens if you are not logged into the site.
It is strange that I did not notice this in incognito mode. But, those screenshots that I sent, I am also unlogged. This behavior is unclear to me.

Check this version if it fixed the bug?

https://gist.github.com/raingart/12695858bd13e356ac87350edf651193/

**Comment by MarkSpizu** [comment]
The videos were from my personal playlists. So, I was always logged in.

Yes, the new version fixed both issues:

1. Player buttons not disappear after Full screen/Exit full screen.
2. Player has straight corners. 

Thanks a lot!

**Comment by raingart** [comment]
Great. I will close the issue when I release the release.

**Comment by MarkSpizu** [comment]
No premium.
