### ISSUE TITLE
[Bug] Control panel below the player ?, no UI, august 2023

### ISSUE THREAD

**Issue by KamelittaOida** [raingart/Nova-YouTube-extension#103]
hey it's me. greasy PM guy. (or one of them)  
'Control panel below the player ? ' shows no UI at all.  
It started happening in private mode 1-2 weeks ago but I thought someone will catch it. They rolled it out for everyone now.  
btw thanks for that feature. I usually always bugged the UI with the mouse and placed the mouse over the UI so it doesn't disappear. thanks 👍

btw did you see? they even added UID URL to the profile pages now. I think this wasn't there yesterday. 

 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0
 - Violentmonkey	extension	2.15.0	true	{aecec67f-0d10-4fa7-b7c7-609a2db280cf}
 - // @version         0.43.4

**Comment by raingart** [comment]
I haven't received this update yet. When it arrives I will update the plugin.

#102

Try to install the specified script. It temporarily fixes the bug

**Comment by KamelittaOida** [comment]
oh someone already posted.  
-.- I didn't see that post. or more like opened github and walked away then didn't refresh.  
and the titanic continues @ you pointing out import/export feature etc.

the script allows it to work.

**Comment by raingart** [comment]
fixed in release. Please update
