### ISSUE TITLE
[Bug] Most of the Theater Modes Are Not Working

### ISSUE THREAD

**Issue by MayouKurayami** [raingart/Nova-YouTube-extension#104]
- Browser: Chrome 115.0.5790.171
 - Violentmonkey 2.13.3 (I also tried the chrome extension version, same issue)
 - Nova 0.43.4
 - Happens on all videos

Theater modes don't seem to do anything. 
For example, I selected "full-viewport" and the result looks exactly the same as the default theater mode.
The only mode that works is "redirect to embedded".

**Comment by raingart** [comment]
Yes confirm.
The reason is that youtube cannot decide to change its main element or leave the old name

replace
```
#player-wide-container',
```
on
```
#ytd-player',
```
