### ISSUE TITLE
[Feature] YouTube Premium Video quality 

### ISSUE THREAD

**Issue by LanGsA0** [raingart/Nova-YouTube-extension#107]
When using YouTube Premium, some 1080p videos have a high bitrate video option as a premium feature. (1080p Premium HD)
Even when I set the video quality to maximum, the quality option is not selected. Please make it possible.

**Comment by raingart** [comment]
You can enter this command in the browser console. After send me the output
```
movie_player.getAvailableQualityLevels()
```

**Comment by LanGsA0** [comment]
> You can enter this command in the browser console. After send me the output
> 
> ```
> movie_player.getAvailableQualityLevels()
> ```

movie_player.getAvailableQualityLevels()
(7) ['hd1080', 'hd720', 'large', 'medium', 'small', 'tiny', 'auto']

It's 1080p Premium on the player, but not in QualityLevels....

**Comment by LanGsA0** [comment]
> Change the quality to free (for example 360p) Enter this code in the browser console. And then change the Premium quality quality. After send me the output
> 
> ```
> movie_player.addEventListener('onPlaybackQualityChange', quality => {
>    console.debug('quality ',quality);
>  });
> ```

movie_player.addEventListener('onPlaybackQualityChange', quality => {
   console.debug('quality ',quality);
 });


undefined

**Comment by LanGsA0** [comment]
movie_player.addEventListener('onPlaybackQualityChange', quality => {
console.debug('quality ',quality);
});

After running it, it will print undefined. There is no output.

**Comment by LanGsA0** [comment]
> movie_player.addEventListener('onPlaybackQualityChange', quality => { console.debug('quality ',quality); });
> 
> After running it, it will print undefined. There is no output.

movie_player.addEventListener('onPlaybackQualityChange', quality => {
console.debug('quality ',quality);
});

After running it, it will print undefined. There is no output.

**Comment by raingart** [comment]
@LanGsA0 hi, I found a new API
You can check it in the console
if it works it should return an array

`movie_player.getAvailableQualityData().find(q => q.qualityLabel.includes('Premium'))`
