### ISSUE TITLE
[Feature] Return old Youtube layout

### ISSUE THREAD

**Issue by Coldblackice** [raingart/Nova-YouTube-extension#108]
I'm in disbelief at how horrifically awful Youtube's new design/layout is. Clearly YT has nothing to show the shareholders so they scramble the chess pieces around the board to say they're "innovating". I digress. Would it be possible to add the ability to revert to the old layout?

I've heard it's being rolled out on an account-by-account basis, so it may be prudent saving some snapshots of the old layout for diff-comparing them with the new layout in order to see all that's being changed. Perhaps there's more being changed than mere surface-level visuals.

**Comment by raingart** [comment]
I have seen several projects that return designs over a period of time.
- [7ktTube](https://7kt.se/)
 - https://github.com/adamlui/youtube-classic
 - https://github.com/lightbeam24/CustomTube

I recommend that you use yt-mirrors
 - https://piped.video/
 - [Invidious](https://yewtu.be/)

**Comment by raingart** [comment]
https://greasyfork.org/en/scripts/485622-startube13

**Comment by raingart** [comment]
https://chromewebstore.google.com/detail/customtube-restore-the-ol/iedffooliepgabiihipcbokboecnfcbe

**Comment by raingart** [comment]
https://greasyfork.org/en/scripts/470453-youtube-pre-may-2021-look-for-yoir-script

**Comment by raingart** [comment]
https://greasyfork.org/en/scripts/479330-alternative-video-page-layout-for-rehike
https://greasyfork.org/en/scripts/485622-startube

**Comment by raingart** [comment]
https://github.com/lightbeam24/CustomTube

**Comment by raingart** [comment]
https://greasyfork.org/en/scripts/449245-youtube-redux-plus
https://greasyfork.org/en/scripts/493290-classic-youtube-layout

**Comment by raingart** [comment]
https://greasyfork.org/en/scripts/480312-compact-youtube-layout

**Comment by raingart** [comment]
https://greasyfork.org/en/scripts/498560-project-vorapis
