### ISSUE TITLE
ads filter

### ISSUE THREAD

**Issue by ChimChamp** [raingart/Nova-YouTube-extension#109]
0.43.5 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
youtube is embedding youtube video ads on the homepage and it is being picked up as a video and autoplaying despite being blocked by an adblocker, so a way to make it not autoplay only on the homepage of youtube would probably fix the issue

**Comment by raingart** [comment]
advertising can be easily disabled using ad filters of any ad blocker
https://filterlists.com/
Nova has no intention of duplicating ad blocker functionality

**Comment by raingart** [comment]
I came across a script. It intercepts ad requests and replaces them. The script is quite complex. If you can't find effective filters, then this script can help

https://greasyfork.org/en/scripts/32626-disable-youtube-video-ads
