### ISSUE TITLE
Error warnings in "chrome://extensions/?errors=" / Broken UI for German lang

### ISSUE THREAD

**Issue by big-cat-loaf** [raingart/Nova-YouTube-extension#110]
[www.youtube.com-1698313189213.log](https://github.com/raingart/Nova-YouTube-extension/files/13175756/www.youtube.com-1698313189213.log)
[www.youtube.com-1698313157394.log](https://github.com/raingart/Nova-YouTube-extension/files/13175758/www.youtube.com-1698313157394.log)
(could be from outher extensions) 
![Screenshot 2023-10-26 115023](https://github.com/raingart/Nova-YouTube-extension/assets/100969549/e233bab8-6762-4d38-95a6-6c5f1e7b6293)
6872a89)
![Screenshot 2023-10-26 115009](https://github.com/raingart/Nova-YouTube-extension/assets/100969549/33ecfac7-f77d-4042-bc6b-1fd82636183a)
![Screenshot 2023-10-26 114952](https://github.com/raingart/Nova-YouTube-extension/assets/100969549/c9cd9692-e860-4d64-adb3-dbfbce4070d2)
![Screenshot 2023-10-26 115050](https://github.com/raingart/Nova-YouTube-extension/assets/100969549/136b49bc-93ca-4eba-9559-5e2fa399ff8d)

 - Browser:  Version 118.0.5993.88 (Official Build, ungoogled-chromium) (64-Bit)
 - Nova: 1.43.5 (App)

**Comment by raingart** [comment]
`Uncaught Error: Extension context invalidated.` - occurs when the connection between context scripts (those that are loaded on the current page of the site) and background (which loads them) is lost. For example, you reloaded the extension without reloading the page

`Unrecognized manifest key 'browser_specific_settings'.` - indicates unrecognized Chromium parameters that are used exclusively in Firefox

`setVideoCount channelld: empty undefined` - exception in plugin [channel-videos-count]. indicating that the plugin did not find channel_id on the page. A mistake I know. I don't want to fix it. So the only solution is to specify the delay in ms. For example, wait 1sec and hope that the channel_id parameter appears. There is no reliable way other than constantly monitoring the presence of this parameter.

`Pattern attribute value ^(AlzaSy)[\d\w-]+ is not a valid regular expression:
Uncaught SyntaxError: Invalid regular expression: /^(AlzaSy)[\d\w-]+/v: Invalid character class` - The key you entered does not match the mask I know. Can you send it to me? For example, by email or here

**Comment by big-cat-loaf** [comment]
thanks for your response I can't reproduce my bug but it could be cause because I use ÖÜÄ or my keyboard is German keyboardlayout.

**Comment by raingart** [comment]
If there are errors or any suggestions please write here
p.s. is the translation into German at least a little clear? Or is it better to remove it?

**Comment by big-cat-loaf** [comment]
I normaly use the English version and well the German version is bit weard, like somethimes the the translation doesn't make sense and english is in the middle and the explantions are in English. 
![Screenshot 2023-10-26 145006](https://github.com/raingart/Nova-YouTube-extension/assets/100969549/10c2da3e-528b-4f51-ae2d-77e485da4990)

**Comment by big-cat-loaf** [comment]
For the App please make wenn you view the parts of the app from a other page it shouldn't look like half cut of. 
![Screenshot 2023-10-26 145416](https://github.com/raingart/Nova-YouTube-extension/assets/100969549/223493ea-2688-46aa-8f2e-088524688a67)

**Comment by raingart** [comment]
I haven't found a better way to fix the localization problem than simply replacing the "long words" in German with English. In these lines:
https://github.com/raingart/Nova-YouTube-extension/blob/master/_locales/de/messages.json#L27-L33

It was possible to reduce the number of characters and add "..." at the end. But I'm not sure about the readability of this option.

@big-cat-loaf you don’t know how you can briefly shorten the words above in German. Perhaps there are synonyms or abbreviations?

p.s. you can temporarily use the extension version. There, due to implementation problems, only plugins are localized. The basic interface remains in English

**Comment by big-cat-loaf** [comment]
There is not really, to my knowledge, a good way to shorten long words, it is in the Nature of German to have long Words, since the we compained with 2 words to one that can only bypassed by making a santance out of it and for other Grammatical reason. But Im not an Expert in my language, so I could be wrong.

**Comment by raingart** [comment]
I left the English localization of the "SAVE" button
