### ISSUE TITLE
'Default tab on channel page' no longer working in 'Click' mode

### ISSUE THREAD

**Issue by Eisys** [raingart/Nova-YouTube-extension#111]
Youtube updated their layout slightly(of course to something worse than before, like always) and now Nova doesn't redirect to the set channel tab, in my case "Videos," in Click mode. Works in Redirect mode still, but I prefer Click.

It works in an old tab I still have open from yesterday, before the update. Not in a new one.
[Old tab](https://i.imgur.com/mjY1fIk.png) -- [New tab](https://i.imgur.com/j3bgAuX.png)

 - Browser: Chrome Version 119.0.6045.33 (Official Build) beta (64-bit)
 - Tampermonkey 4.19.0
 - Nova 0.43.5

**Comment by raingart** [comment]
replace `#tabsContent > [role="tab"]` with `#tabsContent [role="tab"]`.Remove arrow `>`

**Comment by Eisys** [comment]
That fixes it, thanks a bunch!!
