### ISSUE TITLE
[Bug] Expands video description NOT work

### ISSUE THREAD

**Issue by gabri25ele** [raingart/Nova-YouTube-extension#112]
Enable expands video description dosn NOT open the full text video description.

 - Browser: Firefox 119
 - Violetmonkey 2.16
 - 0.43.6

**Comment by gabri25ele** [comment]
I used a clean installation (Firefox, violentmonkey, Nova-YouTube-extension)
you can see here
https://www.dropbox.com/scl/fi/c18cois6qzrqn25g5pg8d/Video_231102135633.mp4?rlkey=qst55qy5psojtq7uxglo1bzjh&dl=0

**Comment by gabri25ele** [comment]
It's always the same but I noticed that if I **reload the page**, the description opens.
it's as if a second load is needed to enable the option.
If you want see a firefox portable, I create, can download here https://easyupload.io/5ikhv0

**Comment by raingart** [comment]
I removed "always" and now by default activation occurs when you hover over the description section

**Comment by raingart** [comment]
Oh shit, it's broken again. The store ver is broken now

Here's the [worked ver](https://gist.github.com/raingart/1f99edf3158ad6babdd1846a6422a72b). Should now work on hover cursor

**Comment by gabri25ele** [comment]
there is no hope for "always"?
it's strange.
Enhancer for YouTube addon has no problem with this option.

**Comment by raingart** [comment]
"always" has been fixed and returned in the new version

**Comment by gabri25ele** [comment]
I can't download the script 😭

**Comment by raingart** [comment]
https://greasyfork.org/en/scripts/433360-nova-youtube

https://openuserjs.org/scripts/raingart/Nova_YouTube
