### ISSUE TITLE
[Bug] Spacebar shortcut to stop video has stopped working

### ISSUE THREAD

**Issue by J4CKED** [raingart/Nova-YouTube-extension#116]
The spacebar shortcut to stop video has stopped working.
I can only resume playback with the spacebar key. 
Probably it worked fine yesterday.

After deactivating Nova, the spacebar works in both cases.

 - Browser: Browser: Firefox 113.0.2 x64
 - Violentmonkey v2.16.0
 - Nova 0.43.7

**Comment by raingart** [comment]
fixed in beta
https://gist.github.com/raingart/1f99edf3158ad6babdd1846a6422a72b

The error is that youtube does not show stop-preview and the plugin blocks playback until the button on the play button is manually activated, the button on the player. But both of these elements are hidden, or rather they are not there.

I don't know if this is a temporary solution from YouTube or a permanent one. Let's wait and see

**Comment by J4CKED** [comment]
The beta version does not work.

With the following script + Nova pause spacebar key works - almost perfectly, because you have to click 2 times to start playback. But stopping and resuming is fine.
https://greasyfork.org/en/scripts/478857-youtube-spacebar-to-play-pause-videos

**Comment by raingart** [comment]
The beta it works for me both through a click and the spacebar

https://github.com/raingart/Nova-YouTube-extension/assets/13064767/9babbd44-1503-4fbe-bb3a-769d9a4dcaea

**Comment by J4CKED** [comment]
After turning off "Video autopause" in Nova spacebar works.

**Comment by raingart** [comment]
Both of these plugins are mutually exclusive
I seem to have taken into account the conflict and "Video autopause" should [stop working](https://github.com/raingart/Nova-YouTube-extension/blob/master/plugins/player/autopause.js#L39) if "Stop video preload" is enabled


The "Video autopause" plugin is currently broken. I corrected it in the dev version. To combat advertising, Youtube has increased the priority of its own player API and decreased the priority of the standard HTML5-video API

**Comment by raingart** [comment]
to fix "Video autopause" plugin
replace
`this.paused || this.pause()`
to
`this.paused || movie_player.pauseVideo()`

**Comment by raingart** [comment]
fixed in the new ver.
