### ISSUE TITLE
[Bug] Default video setting vs Manually change video quality

### ISSUE THREAD

**Issue by J4CKED** [raingart/Nova-YouTube-extension#117]
If I set the default video quality in Nova, e.g. 240p, I cannot manually change it to a higher quality in the youtube player.

 -  Browser: Browser: Firefox 93 x64
 -  Violentmonkey v2.16.0
 -   Nova 0.43.8

**Comment by raingart** [comment]
I confirm 
there is a serious problem with the plugin, reasons:
- logical. The error appeared in version .43.3
- a syntax error. When activating "quality for Music". The bug appeared in the last release (.43.8)

**Comment by raingart** [comment]
beta https://gist.github.com/raingart/a83804b01b7af45796cbe0a740f7899b

**Comment by J4CKED** [comment]
Thank you.
