### ISSUE TITLE
[Feature] Automatic Loop video

### ISSUE THREAD

**Issue by yue374** [raingart/Nova-YouTube-extension#119]
I frequently utilize the repeat feature to enhance my music listening experience. Would it be possible to incorporate this functionality into your userscript? 
If possible, it would be better if a certain period of time could be repeated in the video
![image](https://github.com/raingart/Nova-YouTube-extension/assets/139092243/b2b5b660-b240-4ea7-9ed4-9076c9c8c2d8)
Thank you for reading!

**Comment by raingart** [comment]
In previous versions there was such a plugin. But I thought that it would be convenient to enable this function through the context menu (as in the screenshot)

https://github.com/raingart/Nova-YouTube-extension/blob/f4e94b6ba676c53c58e131a0376b8cd592c07606/plugins/player/loop.js

Probably my experience and frequency of using this function is different from yours. Therefore, the standard functionality of the player is enough for me (via the context menu)

can you describe how you want it to function?
 - Should the setting be the number of plays?
 - or automatically activated on music videos
 - there is a special plugin that can save parameters for individual channels (Add button "Save state for specific channel" / Add button "Save params for the channel" [save-channel-state])

**Comment by yue374** [comment]
I think setting automatic loop in some special channel is great idea, example I listen music most time in "vevo channel", channel name support wildcard syntax maybe better, because some channel have same name contain word "music"

**Comment by raingart** [comment]
There is a global plugin `Add button "Save params for the channel"` it is responsible for activating some enabled plugins for certain channels

**Comment by raingart** [comment]
I forgot to say that Nova has a music detection function. It defines most of the music. But sometimes (often if the channel is music) then a false detect

**Comment by yue374** [comment]
> check it (click "RAW" to install)
> 
> https://gist.github.com/raingart/a83804b01b7af45796cbe0a740f7899b

Thank you for reply, but when I click install this, userscript seem not work, missing nova button, all my setting gone... I using Violent monkey v2.16.0

**Comment by yue374** [comment]
Loop button work fine, but if I switch another video, it can't loop again, so I need click loop button every videos, there is anyway make it remember? And in music video won't automatic loop, example video:
https://www.youtube.com/watch?v=tNxUxm3-658

**Comment by raingart** [comment]
I removed all functions related to music videos
and made it almost an analogue of the built-in loop function. The only difference is that the plugin remembers the state and applies it to the next video. And the built-in function only affects the current video

**Comment by yue374** [comment]
Thank you so much, now it working perfect!
