### ISSUE TITLE
Unable to load theater mode plugin

### ISSUE THREAD

**Issue by nohaboat** [raingart/Nova-YouTube-extension#124]
Error only if theater mode plugin is on. The error message is - Failure when async-call of when of one Nova Youtube Plugin.

trace: unhandledrejection

TypeError: el.theaterModeChanged_ is not a function at chrome-extension://eelcddldbopnbgepcgmapnbpmipaaaih/plugins/player/theater-mode.js:43:16

url: all videos (https://www.youtube.com/watch?v=96wBlCna8I4)

userAgent: 1.44.0 | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

May be problem is that there is no option available for ignore playlist dropdown list.
![Screenshot from 2023-12-03 18-42-00](https://github.com/raingart/Nova-YouTube-extension/assets/115650099/70bbde68-dcd2-4b37-94d1-a909fe6fe530)

**Comment by raingart** [comment]
No, the reason is that Youtube renamed the API call

Fixed version updated
