### ISSUE TITLE
Full/Detailed view count and upload date all the time.

### ISSUE THREAD

**Issue by Eisys** [raingart/Nova-YouTube-extension#127]
So I've been using a script that brings back the old under-video layout(name, description, etc.)
Recently it has started being buggy and not activating all the time.

So now I'm forced to use the new disgusting layout.

I can make it work visually with my custom CSS style but I can't get the exact view count and upload date to show without expanding the description.

So the feature request is to please have an option to show the full view count and exact upload date all the time.

I would like this https://i.imgur.com/9fFOxwz.png to show all the time, instead of this shortened crap: https://i.imgur.com/sxWdOPx.png

Thank You!

**Comment by raingart** [comment]
There are currently two solutions for Nova
 - plugin "Description section in popup". He copies a line from the description and adds it under the video. But sometimes when updating it displays data from the previous video
 - "Displaying date format" - it uses an API request. But it doesn't show the number of views. Maybe I'll fix this someday

**Comment by Eisys** [comment]
[Yeah I used this one](https://greasyfork.org/en/scripts/478159-youtube-2021-layout)

The "Displaying date format" works decently well for me. Thanks. The exact upload date is more important to me than full view count.

But it would still be better if the normal description preview showed it. 
[This addon already can show the full view count instead of the shortened one, just like I'd want](https://greasyfork.org/en/scripts/405614-youtube-polymer-engine-fixes) but it doesn't do the upload date. And I don't really want a whole seperate script just for one function.
I quickly checked out the code for this feature, hoping he did simply with CSS but it seemed pretty complex for such a single switch. 

The info is **right there** and barely any longer than the shortened version, WHY would they shorten it in the first place.. I can't understand the idiots who make these decisions at Google/Youtube.

**Comment by raingart** [comment]
>The info is right there and barely any longer than the shortened version, WHY would they shorten it in the first place.. I can't understand the idiots who make these decisions at Google/Youtube.

There, once in a certain period you need to provide the “result” of your work. And changes in design are most clearly reflected in reports.

**Comment by raingart** [comment]
added the “Show number of views” option to the “Date format display” plugin

https://openuserjs.org/scripts/raingart/Nova_YouTube

**Comment by Eisys** [comment]
Thank you!

And thank you for all the work you do with Nova. I could not use Youtube without it.
