### ISSUE TITLE
[Feature] Option to move transcript back into the three dot menu

### ISSUE THREAD

**Issue by pointydev** [raingart/Nova-YouTube-extension#128]
A while back, YouTube moved the button to open the transcript from the three dot menu in the stats bar to the bottom of the description, even for a while having a button that would force the user to go to the bottom of the description even when the transcript button was still in its original place. An option to revert this would be great.

Thanks,
Elliott

**Comment by pointydev** [comment]
When I say button, I mean the option in the dropdown, much like the report button that will not expand into the visible buttons when the width is changed. I understand this isn't as easy as moving elements, but I use the transcript very often and would very much appreciate an option like this.

**Comment by pointydev** [comment]
I was hoping for the button version to open the normal transcript popup (like you've done with the expand option) instead of an external site. Perhaps the external site could be a toggle option under this new plugin?
I was also hoping for it to be located in the actions dropdown menu, although this is minor. However, may I suggest putting it after the `#actions` element instead (represented with an icon).

**Comment by raingart** [comment]
add new plugin "Show transcript"

**Comment by pointydev** [comment]
LGTM 👍

**Comment by pointydev** [comment]
Also, you may want to consider adding `yt-spec-button-shape-next yt-spec-button-shape-next--tonal yt-spec-button-shape-next--mono yt-spec-button-shape-next--size-m` as classes instead of the explicit CSS you've added to `#nova-transcript-button` to be more in line with the buttons around it (may also need a bit of padding/margin adjustment). See result of that below:
![class updates](https://github.com/raingart/Nova-YouTube-extension/assets/22241432/244d3f69-48a9-491f-84f4-caa25be15d9d)

Also, minor bugs found, clicking the button multiple times makes it so that it opens multiple instances of the transcript modal, meaning you have to click multiple times to close it, and the title attribute is still set to "Download Transcript" even though we're just opening the modal.

**Comment by raingart** [comment]
I forgot to say that the plugin is compatible with the `Add button "Save params for the channel"` plugin
