### ISSUE TITLE
Stop video preload make control panal unusable [Bug]

### ISSUE THREAD

**Issue by jhiajhainjhon** [raingart/Nova-YouTube-extension#129]
"Stop video preload" feature make control panal unclickable, can't trigger those buttons even when toggle to.
Need access to live, subtitle and setting

Browser: Brave [version1.61.104 Chromium: 120.0.6099.115]
Tampermonkey v5.0.0
Nova YouTube 0.45.0

**Comment by raingart** [comment]
fixed
