### ISSUE TITLE
[Bug] Pinned player while scrolling conflicts with "Thumbnail Rating Bar for YouTube" addon

### ISSUE THREAD

**Issue by GoodTimesAhead** [raingart/Nova-YouTube-extension#130]
- Browser: Firefox 120
 - ViolentMonkey 2.16.0
 - Nova 0.45.0

The addon "Thumbnail Rating Bar for YouTube" uses z-index: 999 for the rating bars below every thumbnail. So when the player is pinned (I use mine bottom right, size: 2) the rating bars appear above the player.

**Comment by raingart** [comment]
fixed
