### ISSUE TITLE
YouTube Auto-Liker [Feature]

### ISSUE THREAD

**Issue by zkisaboss** [raingart/Nova-YouTube-extension#131]
This feature should automatically likes YouTube videos when they reach a specified watch threshold. My previous auto-liker userscript broke, and the creator isn't updating it anymore.

**Comment by raingart** [comment]
test it
https://gist.github.com/raingart/2567b79fb3fc977d3096adb460e3ef3f

**Comment by zkisaboss** [comment]
So it managed to trigger once, which is a good sign, but the timing was off and I couldn't get it to work again.

**Comment by zkisaboss** [comment]
I also noticed the automatic quality selector became wonky but i'm not sure if that's related to the auto-liker.

**Comment by raingart** [comment]
quality selector doesn't work because this is a test version and the plugin looks for premium quality, doesn't find it and breaks


try again
https://gist.github.com/raingart/2567b79fb3fc977d3096adb460e3ef3f

**Comment by zkisaboss** [comment]
I tested and I can't get it to trigger the like button.
I used to use this script https://greasyfork.org/en/scripts/33865-youtube-auto-liker, but it no longer works.
I think yours could be improved by checking the watchtime in intervals and stopping when the video is liked. 
This is just an idea, let me know what you think...


`let observer, mutationCount = 0;

const doSomething = () => {
    // Impliment Auto-Liker and observer.disconnect(); when triggered
    // Impliment eventlistener for when the user manually likes the video, or somehow check if the video is alrady liked.
};

const handleMutation = mutations => {
    if (/* put condition here */) doSomething();
    else observer.disconnect();
};

const startObserver = () => {
    observer = new MutationObserver(handleMutation);
    observer.observe(document.body, {
        childList: true,
        subtree: true
    });
};

const resumeMutation = () => {
    mutationCount = 0;
    if (window.location.href.includes('watch')) startObserver();
};

document.addEventListener('yt-navigate-start', resumeMutation);`

**Comment by raingart** [comment]
you set the test threshold to 0.1?

The principle of operation is that the plugin takes into account viewing time and not playback position

that is, if you seek until the end of the video, the plugin will not activate

for example, if you specify 0.1 this will mean that the plugin will work if you have watched 10% of the video

**Comment by raingart** [comment]
the script you are using is not working due to updates to youtube like/dislike selectors
```
LIKE_BUTTON: 'ytd-watch-metadata #actions like-button-view-model button'
DISLIKE_BUTTON:  'ytd-watch-metadata #actions dislike-button-view-model button'
```
