### ISSUE TITLE
[Feature] Pin Header when Theater mode is set to full-viewport

### ISSUE THREAD

**Issue by GoodTimesAhead** [raingart/Nova-YouTube-extension#132]
Full viewport is good but it would be nice to have the header always on instead of needing to mouse over. Can we have this as an option? Enhancer for Youtube used to have this they called it "Expand Video". Video would start below header and expand to full viewport height.

**Comment by raingart** [comment]
try `offset` mode

**Comment by GoodTimesAhead** [comment]
Offset doesn't do anything for me.

Here's the difference between offset and enhancer. The closest thing is full-viewport

https://i.imgur.com/lfVws8p.jpg

https://i.imgur.com/qjosHnp.jpg

**Comment by GoodTimesAhead** [comment]
> check beta https://gist.github.com/raingart/2567b79fb3fc977d3096adb460e3ef3f

Yes perfect! Thanks

**Comment by GoodTimesAhead** [comment]
The latest one breaks it a little with the offset. 

https://i.imgur.com/Zxt90KS.jpg

**Comment by GoodTimesAhead** [comment]
I did but part of the title/description/buttons still stays behind the video.

**Comment by GoodTimesAhead** [comment]
> check the element css-style`#container #movie_player`
> 
> it has these parameters?
> 
> ```
> z-index: 2020;
> background-color: black;
> ```
> 
> ![Screenshot from 2023-12-21 18-14-37](https://private-user-images.githubusercontent.com/13064767/292258701-07f44565-9808-475c-a5ee-51a38347e4b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzU2ODQsIm5iZiI6MTcwMzE3NTM4NCwicGF0aCI6Ii8xMzA2NDc2Ny8yOTIyNTg3MDEtMDdmNDQ1NjUtOTgwOC00NzVjLWE1ZWUtNTFhMzgzNDdlNGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE2MTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNmQwYWQzYTliZGIyYzFjMDU2MTA1ZGU2Y2Q3NzY5YTRlM2FhYTA4ZjQxNTU3MDJjYWZlNDVmNmQ2MDZkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HRr2zZM2exY1p6FRwS67qiyqfN_V4BPxpexBMsxpk6U)

Yes.

The problem is the height of the video changes but all the rest of the page doesn't get adjusted down so part of it stays behind the video.

**Comment by GoodTimesAhead** [comment]
If I add margin-top: 10rem to the div with id="columns" it seems to fix it but I don't know how sustainable this is.

**Comment by GoodTimesAhead** [comment]
That would just hide everything but the video.
I added this and it does the trick

`#columns {  margin-top: 13em !important; }`

**Comment by raingart** [comment]
agree. try this rev
https://gist.github.com/raingart/2567b79fb3fc977d3096adb460e3ef3f

```
ytd-watch-flexy[theater]:not([fullscreen]) #columns {
    position: absolute;
    top: 100vh;
 }
```

**Comment by GoodTimesAhead** [comment]
> agree. try this rev https://gist.github.com/raingart/2567b79fb3fc977d3096adb460e3ef3f
> 
> ```
> ytd-watch-flexy[theater]:not([fullscreen]) #columns {
>     position: absolute;
>     top: 100vh;
>  }
> ```

Yeah this solves it and it's the most "correct" way to do it 👍
