### ISSUE TITLE
[Feature] Anti Shorts

### ISSUE THREAD

**Issue by zkisaboss** [raingart/Nova-YouTube-extension#137]
This YouTube Shorts Blocker still works, but the code is shitty, and it logs a bunch of random shit to the console. It would be a great feature for your script.

https://greasyfork.org/en/scripts/441709-youtube-anti-shorts

**Comment by zkisaboss** [comment]
Happy New Year!!! 🎉🎉

**Comment by misspent** [comment]
You can use [uBlock Origin](https://ublockorigin.com) to do this with ease: [Remove Shorts + other stuff](https://www.reddit.com/r/uBlockOrigin/wiki/solutions/youtube#wiki_shorts)

I used to use that script too, but it ended up conflicting with other stuff and spamming the console like you said, so I ended up using the above, it works a lot better and is much smoother than the script.

**Comment by zkisaboss** [comment]
Thanks for the suggestion, I'll try it out and let you know if it works.

**Comment by zkisaboss** [comment]
It worked for me, thanks. These were the only ones I enabled, the rest didn't appear to do anything.

```
! YT Homepage and Subscriptions - Hide the Shorts section
youtube.com##[is-shorts]
! YT Menu - Hide the Shorts button
www.youtube.com###guide [title="Shorts"], .ytd-mini-guide-entry-renderer[title="Shorts"]
! YT Search, Channels and Sidebar or below the player - Hide the Shorts sections
www.youtube.com##ytd-reel-shelf-renderer
```
