### ISSUE TITLE
[Bug] Export/Import with UserScript

### ISSUE THREAD

**Issue by arogl** [raingart/Nova-YouTube-extension#138]
I am using the userscript version on 2 different machines, they both run the latest Chrome, Tampermonkey beta and your script.

I am able to export the settings form both machines, but when I import on 1 machine, it says imported, but none of the settings are changed.

 - Browser: Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Tampermonkey Version 5.0.6192
 - Nova YouTube 0.46.0

I have not tested the non-beta version of Tampermonkey

**Comment by zkisaboss** [comment]
### Temporary fix.

1. Go to your computer with the preferred settings
2. Click on your extension
3. Open the dashboard
4. Select the "utilities" tab (top right) 
5. Enable all settings under the "general" section
6. Export your settings to google drive
7. Go to the same place on your other device (steps 1-6)
8. Click "show backups"
9. Import the saved settings

**Comment by raingart** [comment]
Tampermonkey does not allow you to directly edit script settings
Violentmonkey allows you to edit settings. You can also activate Sync there

![Screenshot_2](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/2beee17c-036f-4513-975a-e861bbe642c4)

**Comment by raingart** [comment]
The new ver. changed load backup method
