### ISSUE TITLE
[Bug] Ugly bar above the comment section.

### ISSUE THREAD

**Issue by zkisaboss** [raingart/Nova-YouTube-extension#139]
The [ugly bar](https://i.gyazo.com/0cdf164684348dd8885d37c0cd4de354.png) doesn't go away with "hide metadata" enabled. I found a useful extension, [Unhook](https://chromewebstore.google.com/detail/unhook-remove-youtube-rec/khncfooichmfjbepaaaebmommgaepoid), which has a feature (Hide Merch, Tickets, Offers) similar to Hide Metadata, but blocks additional annoyances.

 - Browser: Chrome Version 120.0.6099.129 (Official Build) (arm64) 
 - Tampermonkey Version 5.0.0 
 - Nova Version 0.46.0 
- Video where bug occurs: [Game Theory: Why Everyone HATES YouTube Shorts… And You Should Too!](https://www.youtube.com/watch?v=0Igj3qI0GBA)

**Comment by raingart** [comment]
The funny thing is that this advertising is tied to a specific region. I don't see it in myself

There is a fast online editor for extensions. I added alias call `cx` in `chrome://settings/searchEngines`

https://robwu.nl/crxviewer/?crx=khncfooichmfjbepaaaebmommgaepoid

![Screenshot_1](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/c8a4bf2e-7c6a-4029-af7b-eab4e991e982)

```
#clarify-box,
#offer-module,
#ticket-shelf,
.ytp-drawer,
yt-alert-with-actions-renderer,
ytd-merch-shelf-renderer,
ytd-metadata-row-container-renderer>#always-shown,
ytm-compact-offer-module-renderer,
```

**Comment by zkisaboss** [comment]
I am still trying to understand what the online editor is for.

It would be great if you made "hide metadata" more robust, like Unhook's version, but it's not necessary. Feel free to close the issue if you think it's not worth the time.

**Comment by zkisaboss** [comment]
This uBlock Origin filter seems to also fix the problem: `www.youtube.com##ytd-merch-shelf-renderer`

**Comment by raingart** [comment]
added new ver
