### ISSUE TITLE
Settings are not applied when expanding video from a queue built on the front page

### ISSUE THREAD

**Issue by tyaremco** [raingart/Nova-YouTube-extension#145]
1. Open youtube.com in a new tab
2. Add any video to the queue using "add to queue" hover button
3. click "expand" button in the upper left of the mini player

Result:
Nova settings fail to manifest.  At minimum: any additional player buttons and the playlist autoplay toggle fail to appear.  Refreshing the page fixes the issue.

 - Nova 0.46.1

**Comment by tyaremco** [comment]
> What prevents you from opening a window with a player in the background or next to it? and switch to it if necessary

I don't care about the miniplayer at all but when queuing a video, the default behaviour is to show the miniplayer (it doesn't seem like the "disable miniplayer" setting stops this either) with the queue beneath it.   I see no way to open the first video of the queue without using the "expand" button.  **It's the queuing feature I'm interested in.**

Building a queue from a non-video page and having Nova settings applied when the first video loads is the desired behaviour.

### The use case is:

1. open youtube front page to see what is recommended OR open a channel page to the video archive
2. queue preferred videos 
3. start playing queue on page of first video (miniplayer not needed)

&nbsp;

Is there a possibility of replacing the "expand" button with a direct link to the queue, forcing a page refresh?

**Comment by raingart** [comment]
I used the dirty reload trick.
 there shouldn't be any problems with it

**Comment by tyaremco** [comment]
Hhmm, I get the same behaviour as before: settings not applied.  No page refresh took place either...

**Comment by tyaremco** [comment]
OK, it's working but it gets stuck in a refresh loop.

**Comment by raingart** [comment]
Why does the url change every time refresh? if yes, which part?

**Comment by tyaremco** [comment]
`&index` keeps incrementing.  You need to add at least 2 videos to queue to reproduce.

**Comment by raingart** [comment]
I tried to add several, but for some reason I don’t have any parameters in the url except id

ok I'll exclude index now

**Comment by tyaremco** [comment]
Works great now!  Thank you for doing this for me, I appreciate it.

**Comment by tyaremco** [comment]
Actually a slight modification needed.  Once Nova applies its settings to a video, subsequent queues from non-video pages work fine and a reload is NOT needed.

For example.
1. new tab, youtube.com
2. load a video 
3. return to front page by click logo in upper left
4. queue videos
5. click expand

Result: Nova settings are applied and behave as expected.

Currently we are refreshing for **every** non-video page queue but it is only necessary in the case where a video page has not yet been loaded that session.

**Comment by raingart** [comment]
it took longer

should work work correctly
