### ISSUE TITLE
Option for Default Speed

### ISSUE THREAD

**Issue by tyaremco** [raingart/Nova-YouTube-extension#148]
Although Youtube persists a speed setting per session, it always gets reset to 1.00 if the tab is ever closed.  And if the playback speed is ever changed on a video, that becomes the new default for subsequent videos (and then has to be changed back).

Similar to Default Resolution, this setting would define the starting speed of videos.

**Comment by raingart** [comment]
enable `Playback speed control` > `Speed at startup` - to save in all videos (excluding `Add button "Save params for the channel"`)
choose the `Hotkey` you like. To save in session

optional: enable `Add button "Save params for the channel"`
optional:  `Add custom player buttons` choose `range speed` and `toggle speed`

**Comment by tyaremco** [comment]
Thanks, that's perfect!  I overlooked that setting.
