### ISSUE TITLE
[Bug] Video length badges on thumbnails are being affected by the Speed At Startup setting.

### ISSUE THREAD

**Issue by tyaremco** [raingart/Nova-YouTube-extension#150]
Thumbnails in the sidebar have a little duration badge in the bottom right.  If _Speed At Startup_ is set to 2, all durations will be shown as half the real length.

I don't know if this was intentional, perhaps some people would want that feature.  
If so, maybe have an option to always the show real length?

**Comment by raingart** [comment]
this is not a bug
I will make this feature optional

**Comment by raingart** [comment]
Added new option  `Recalculate overlay time`
