### ISSUE TITLE
[Feature] Add "unlimit" to Playback Speed Control hotkey

### ISSUE THREAD

**Issue by tyaremco** [raingart/Nova-YouTube-extension#151]
Like _Range Speed Unlimit_ but for the playback speed Hotkey.   Otherwise, at speeds greater than 2 adjusting speed with the Hotkey will reset the speed to 2.

**Comment by raingart** [comment]
if you specify more than `2` (like `2.25`) in `Speed ​​at startup`
or make `Step` not a multiple of `0.25` then the limits are removed (unlimit)

The principle of operation is that the plugin tries to use the default API, which has limitations. But if the initial parameters in the settings do not comply with the API limits, then another method of changing the speed is used

**Comment by raingart** [comment]
Btw advanced options are extended the menu
![Screenshot_3](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/d5f0f5d0-58d6-4177-93f1-f571f2cfb325)

**Comment by tyaremco** [comment]
> if you specify more than `2` (like `2.25`) in `Speed ​​at startup` or make `Step` not a multiple of `0.25` then the limits are removed (unlimit)
> 
> The principle of operation is that the plugin tries to use the default API, which has limitations. But if the initial parameters in the settings do not comply with the API limits, then another method of changing the speed is used

This is kind of goofy because it breaks a simple use case:

* startup speed set to `2`
* and a hotkey to bump speed `>2 `

The hot key will fail to work because the initial params are compliant.  But if `startup speed` is increased by `0.05` then the hotkey starts working!

I guess this is fine workaround but its really only practical for my case where my `startup speed` is already at `2`.  

&nbsp;

**If `startup speed` is OFF but `Range speed unlimit` is ON, the behaviour is confusing:**  For example, 
- I CAN use the `speed range slider` to go from `2` to `2.25` by scrolling on it
- but I CANNOT use the `speed hotkey` to go from `2.25` to `2.50`   

Why unlimit only the `speed range slider` but not the `speed control hotkey`?  It's inconsistant.

Better to just have a global `Unlimit Speed Controls` setting in `Playback speed control` which forces the non-API method.

**Comment by tyaremco** [comment]
I edited my comment just before you replied, consider the last line:

> Better to just have a global `Unlimit Speed Controls` setting in `Playback speed control` which forces the non-API method.

Isn't this the best method?  
Setting `Startup Speed` to `2.05` already automatically invokes the `alternate mode` and it works excellent.  
So just include a setting that forces that mode.  That's easy isn't it?  

&nbsp;

Even if you think you're stupid, I think you're doing a great job and a good service!

&nbsp;

PS. There are several channels I can follow easily >2x speed.  One talks so slow and rambling it can even be followed at 3x!  I can link if desired.  But I agree, beyond 3x I cannot see the utility.

**Comment by tyaremco** [comment]
`Save params for channel` button doesn't work for speeds set by the hotkey or range slider in "alternate mode", I guess because the speed in the player is not actually being updated.

**Comment by raingart** [comment]
check it

`Save params for channel` received data from the player API. Fact it worked incorrectly for data not multiple of 0.25
