### ISSUE TITLE
[Feature] Uncap Buffer

### ISSUE THREAD

**Issue by zkisaboss** [raingart/Nova-YouTube-extension#152]
Is it possible to have youtube to continuously buffer the video? If not close this issue, I just think it's a cool idea.

**Comment by raingart** [comment]
All the methods I know come down to background emulation of `player.seek`

here is an active discussion thread
https://www.reddit.com/r/chrome/comments/7gzyka/is_there_a_way_to_force_youtube_to_buffer_an/

https://pastebin.com/ZGcpri47

[Magic Actions for YouTube™](https://chromewebstore.google.com/detail/abjcfabbhafbcdfjoecdgepllmpfceif)
![Screenshot from 2024-01-30 12-12-49](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/4b597a00-9d0b-40e4-aad5-ff6e921c3d2d)

https://extpose.com/ext/nfmmfalangpoddnbmpggkogocecengab **Warning**. The extension transfers data to its own (now inactive server)
![Screenshot from 2024-01-30 12-15-57](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/6aac82bc-091b-4ae8-b144-8f1aa12aaa52)

https://chromewebstore.google.com/detail/smartvideo-for-youtube/lnkdbjbjpnpjeciipoaflmpcddinpjjp (https://www.gtricks.com/youtube/3-simple-ways-to-fully-buffer-youtube-video/)
here the code is minified but I don’t understand how it works

The operating principle is as stupid as possible. If the video is paused and the buffer has reached the limit, but seek emulation starts. That is, it only works during pause. and I'm not sure that the scripts take into account the length of the video and the available browser buffer size. Especially on a multi-hour stream.
I've always found options like this amusing. A huge red button with the inscription "Make everything cool".

**Comment by raingart** [comment]
for test added `Video preload buffer` plugin

**Comment by zkisaboss** [comment]
I'm loving this test version. I tried the preload buffer and it's kinda buggy, but it seems to work better than the other resources you shared, most of which are outdated.
