### ISSUE TITLE
[Feature] Add "Watch Later button on Preview" everywhere

### ISSUE THREAD

**Issue by limex** [raingart/Nova-YouTube-extension#153]
Hi, 
thanks for the great extension.

I have a FR:
As a user I would like to add a video to the Watch Later Playlist when I watch the preview by hoovering. This is more convenient than moving the mouse near the video desciption to the 3 dot menue.

This feature is present on the History page:

![image](https://github.com/raingart/Nova-YouTube-extension/assets/1173039/ddd0fd24-ab86-4b44-a176-d2ea4815ff6e)

but not on ALWAYS on other pages: 

![image](https://github.com/raingart/Nova-YouTube-extension/assets/1173039/22d885df-fe70-46ec-bb5a-2036b8c0cd92)

Sometimes I see the clock symbol on the Subscription Page and the video next to it has none. This is strange.
I understand that this is a feature or a bug by youtube.

But: Can you add it to the extension to show a clock icon allways on the thumbnails on Subscription Page and the Home Page?

Thanks in advance & BR
Günther

**Comment by limex** [comment]
Me:
> This is more convenient than moving the mouse near the video desciption to the 3 dot menue.

You:
> then when you hover over the thumbnail on the right next to the titile, a menu appears and you can add it to the watch list.

We are talking about the same dialog. :)

**Comment by raingart** [comment]
new plugin `Add Watch Later button on thumbnails`

**Comment by raingart** [comment]
Now only works inhttps://www.youtube.com/feed/subscriptions 
a other pages seem to have default "Watch Late" buttons

**Comment by raingart** [comment]
The plugin's operating principle is stupid and unreliable
There is a drop-down menu on the page in one copy. And it is updated and moved for each miniature separately. That is, the Watch Later button is in the singular. And the plugin just very quickly opens the menu and selects the desired item

**Comment by limex** [comment]
This is owesome. Thanks so much.
