### ISSUE TITLE
[Bug] Pin player while scrolling makes text unselectable

### ISSUE THREAD

**Issue by GoodTimesAhead** [raingart/Nova-YouTube-extension#157]
Having this problem since a recent update. Once you scroll down and the pinned window appears any text on the page (comments, description etc) cannot be selected any longer. You have to either scroll back or close the pinned window.

0.46.1 works

**Comment by raingart** [comment]
The reason is the plugin `Pin player while scrolling`

reinstall this version https://openuserjs.org/scripts/raingart/Nova_YouTube

**Comment by GoodTimesAhead** [comment]
Thank you that fixed it.
