### ISSUE TITLE
[Feature] - Volume boost by default

### ISSUE THREAD

**Issue by chaoscreater** [raingart/Nova-YouTube-extension#159]
The disable volume normalization setting doesn't seem to work. I can boost the volume using the hotkey and boost it above 100% and that works great, but volume normalization on/off doesn't make a difference. Here's an example video I tested:

https://www.youtube.com/watch?v=sVLeK0pdfWw

Since I can manually boost the volume level using the hotkey to 200%, it would be great if we can set this as the default volume. At the moment, default volume can only be up to 100% maximum. If volume normalization doesn't work, then the workaround for me would be to set a default boosted volume level of 200%.

 - Browser: Thoriumv120.0.6099.235 
- ViolentMonkey
 - Nova 0.47

**Comment by raingart** [comment]
Normalization works, but not in all videos. Depends on the volume level during encoding.

works
https://www.youtube.com/watch?v=kgPt2mZooss
https://www.youtube.com/watch?v=qfNmyxV2Ncw
https://www.youtube.com/watch?v=EjSvChCF9_M
https://www.youtube.com/watch?v=fqYFkPeYqoI

does not work
https://www.youtube.com/watch?v=AcWygF_e_2M
https://www.youtube.com/watch?v=AwUqgyHGy00

What about the default being higher than 100%. This will require rewriting some of the functionality. I'll see what i can do

**Comment by raingart** [comment]
there are some features and limitations of the plugins
1. `Default level` available more than 100
but if the value is not a multiple of 100. For example, 150, 399, then it will be rounded to the nearest hundredth.

2. if the `Allow above 100%` option is inactive, then you will absolutely not be able to set the value above 100 using hot keys
