### ISSUE TITLE
[Feature] 'Stop video preload' but load the thumbnails instead black

### ISSUE THREAD

**Issue by KamelittaOida** [raingart/Nova-YouTube-extension#160]
hello

if possible, would be great if there was a sub-option to load the thumbnail (e.g. `<link rel="image_src" href="https://i.ytimg.com/vi/ITdISFrIJkU/maxresdefault.jpg">`) instead of displaying the black background.

👍👍❤

**Comment by raingart** [comment]
Hi
Good idea, I'll do it

**Comment by KamelittaOida** [comment]
great thanks 

but maybe optional. I'm sure some will prefer a black bg.

**Comment by raingart** [comment]
new option `Show video preview thumbnail`

This option only works for watch page. I'm not sure if this is necessary for embed

**Comment by KamelittaOida** [comment]
ok I'm sorry for doing this, but I can't figure it out :S 

my current 0.47.0 version has 11k lines and the 'test' update has 26k. size went up from 390k to 1mb

I clicked on Raw, monkey opens, updates: no
I download the Raw, copypaste (utf-8): no

**Comment by KamelittaOida** [comment]
oh no I think you misunderstand. I don't care about the size.

am i supposed to only copypaste? I receive the monkey Reinstall prompt and I do that, but it doesn't end up working. at all. the script doesn't load on a youtube page.

**Comment by KamelittaOida** [comment]
oof. you deleted that video ^^; 
well I remember some. but now since some things have changed. I honestly had no idea JS needed to be compiled too.

ehh let me try

**Comment by KamelittaOida** [comment]
it works and it looks beautiful IMHO, but it seems to need 2 clicks to play. Personally, I don't care, just letting you know.

(funny how my settings got overwritten now, they usually don't. Now going back to hunting down my API key. (i'm not complaining just stating) 😅👍)

> But I thought that not everyone is interested in how cars are repaired or assembled, especially when they just want to drive it

yea like we talked in greasyfork, I can figure some stuff out, but unfortunately I'm not the brightest and the day has only 24 hours. I can barely handle batch.

**Comment by KamelittaOida** [comment]
ah ok. that's why i needed two clicks.
![image](https://github.com/raingart/Nova-YouTube-extension/assets/29007971/4950f276-76fd-4579-a03e-40a9a3175dd7)

>and how to build this thing
https://github.com/raingart/Nova-YouTube-extension?tab=readme-ov-file#development

ok thanks 👍

>you can see the key or refresh it somewhere here

wasn't necessary but thank you. 
omg key created jun 2023. time flies
