### ISSUE TITLE
[Feature] Expand description?

### ISSUE THREAD

**Issue by krisu5** [raingart/Nova-YouTube-extension#163]
It seems that it's gone now, is it possible get it back?

**Comment by raingart** [comment]
I found out that youtube save the previous state for the guide panel and description section
Therefore, I decided to remove the “useless” plugins
If necessary for you, I can return it.

**Comment by krisu5** [comment]
> I found out that youtube save the previous state for the guide panel and description section

Huh, for me it doesn't for some reason. 😕 Personally it's necessary, I downgraded the script to 0.48.0 for time being.

**Comment by raingart** [comment]
I will return the plugin in the next release
