### ISSUE TITLE
[Bug] Hide "clip" button

### ISSUE THREAD

**Issue by jhiajhainjhon** [raingart/Nova-YouTube-extension#164]
Hide "clip" button makes "download" & "save" button also hidden.

 - Browser: Brave Version 1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit)
 -TamperMonkey v5.0.1
 - Nova 0.49.1

![螢幕擷取畫面 2024-03-16 211310](https://github.com/raingart/Nova-YouTube-extension/assets/87281918/50471776-5e07-4bec-b538-9689306e0354)
![螢幕擷取畫面 2024-03-16 210353](https://github.com/raingart/Nova-YouTube-extension/assets/87281918/a99742cc-dec4-4b42-a3cd-e451a7ce7374)
![螢幕擷取畫面 2024-03-16 210409](https://github.com/raingart/Nova-YouTube-extension/assets/87281918/c1cd157d-33a5-4c25-88da-65bdf471621a)

**Comment by raingart** [comment]
remove this line
```
`${SELECTOR_BTN_CONTAINER} #flexible-item-buttons`,
```

**Comment by jhiajhainjhon** [comment]
English is enough for me.
BTW do you know that the localization of Chinese (Traditional) is mixed with Japanese, Korean and Chinese (Simplified)?

**Comment by jhiajhainjhon** [comment]
umm...I think you maybe take it wrong due to my bad English.
I mean there's Japanese, Korean and Chinese (Simplified) translation in the Chinese (Traditional) localization translation.
Even if I use the Chinese (Traditional) localization, there's still some descriptions not in my language and I can't read them.
So I don't really use the Chinese (Traditional) localization in this extension.

![螢幕擷取畫面 2024-03-17 055825](https://github.com/raingart/Nova-YouTube-extension/assets/87281918/60514527-3219-45a1-9244-1a40f83f44d7)
![螢幕擷取畫面 2024-03-17 060948](https://github.com/raingart/Nova-YouTube-extension/assets/87281918/4f99350e-80c1-4337-af83-f07337cc258b)
