### ISSUE TITLE
video preloading bugs

### ISSUE THREAD

**Issue by Shakib436** [raingart/Nova-YouTube-extension#165]
0.49.1 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36?body=0.49.1 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

video preloading should have a button to stop loading or start loading otherwise it brings me to next video.😥😥😥

**Comment by raingart** [comment]
check dev ver

**Comment by Shakib436** [comment]
I mean if I have button to stop and start preloading on youtube webpage, it
will not load video when I pause video as a result this will not disturb
when I pause video,.otherwise it load video automatically and most of the
case it load full video and play next video.I have tried stop preloading
option but still it is not working properly.It is to irritating to data
users.It consume all data at a time.

**Comment by Shakib436** [comment]
dev version is ok

**Comment by raingart** [comment]
added button
reinstall dev ver

**Comment by Shakib436** [comment]
Thanks a lot.
