### ISSUE TITLE
cannot change off of default quality

### ISSUE THREAD

**Issue by ChimChamp** [raingart/Nova-YouTube-extension#166]
0.43.5 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
I like using the default quality setting because the music version is really useful, but sometimes I want to have normal videos on in the background at a lower quality but it just auto sets it back to the default when I change it, so some way to stop it doing that or access to the music quality option without the other active would be nice

**Comment by raingart** [comment]
Weird. Have you enabled the option `Save manual selection for next video`?
it should overwrite all other states (for music and fullscreen)

and the message should appear in the console 
```
console.info(`keep quality "${quality}" in the session`);
```

ps you are using an outdated version. Now actual v0.49.1

**Comment by raingart** [comment]
BTW if you use the plugin `Add custom player buttons` > `quick quality`
then the selected quality will not be applied to the next videos.

**Comment by ChimChamp** [comment]
the save manual selection for next video option worked, thanks!
