### ISSUE TITLE
How to import settings while using Tampermonkey?

### ISSUE THREAD

**Issue by lakshits11** [raingart/Nova-YouTube-extension#17]
*Describe the bug*

 - Browser: Brave latest version
 - Tampermonkey
 - Nova version: 6.6.1

I am clicking on import settings but nothing happens, while when I click on export settings, it quickly exports them.
But having problems importing the settings.

![image](https://user-images.githubusercontent.com/54276661/188300822-46c010b9-cf51-4a45-bb54-2521415ab8a7.png)

**Comment by raingart** [comment]
These are Brave problems. Everything works correctly in other browsers. Let them know if you want.

Tampermonkey does not allow you to directly edit script data, unlike Violentmonkey, for example:
![Screenshot_2](https://user-images.githubusercontent.com/13064767/188306732-a6193192-0e5f-41e1-8c91-01c9df6d0fa9.png)

Also, Brave is good at pretending to be Chrome, which prevents it from being detected and using a different import method for it.

I can suggest that you replace this piece of code yourself:

<details>
  <summary>current/old</summary>
<pre>
   GM_registerMenuCommand('Import settings', () => {
      let f = document.createElement('input');
      f.type = 'file';
      f.accept = 'application/JSON';
      f.style.display = 'none';
      f.addEventListener('change', function () {
            let files =   Array.from(f.files);
            console.log(files);
               return          
         if (f.files.length !== 1) return alert('file empty');
         let rdr = new FileReader();
         rdr.addEventListener('load', function () {
            try {
               GM_setValue(configStoreName, JSON.parse(rdr.result));
               alert('Settings imported');
               location.reload();
            }
            catch (err) {
               alert(`Error parsing settings\n${err.name}: ${err.message}`);
            }
         });
         rdr.addEventListener('error', error => alert('Error loading file\n' + rdr.error));
         rdr.readAsText(f.files[0]);
      });
      document.body.append(f);
      f.click();
      f.remove();
   });
</pre>
</details>

<details>
  <summary>new</summary>
<pre>
GM_registerMenuCommand('Import settings', () => {
       if(json = JSON.parse(prompt('Enter json file context'))) {
           GM_setValue(configStoreName, json);
           alert('Settings imported');
           location.reload();
       } else alert('Import failed');
   });
</pre>
</details>

**Comment by lakshits11** [comment]
Well I used violentmonkey and was able to import the settings.
