### ISSUE TITLE
'Fix channel links in sidebar' doesn't work

### ISSUE THREAD

**Issue by Eisys** [raingart/Nova-YouTube-extension#170]
At some point in the last week or so this great feature has stopped working.
I click on the channel name but it goes to the video still.

 - Browser: Chrome Version 124.0.6367.18 (Official Build) beta (64-bit)
 - Tampermonkey 5.1.0
 - Nova 0.49.2

**Comment by raingart** [comment]
check [dev](https://gist.github.com/raingart/d10ac89efa39222ea5cea3f437834a1d) ver.

**Comment by Eisys** [comment]
Seems to be fixed in the dev version. Thank you so much!!
