### ISSUE TITLE
wrong hyperlink from wiki to userscripts page

### ISSUE THREAD

**Issue by Kodapegir** [raingart/Nova-YouTube-extension#18]
On the wiki page 
https://github.com/raingart/Nova-YouTube-extension/wiki/Stop-developing-NOVA-builds-as-extensions

hyperlink 'userscript' goes to 404 page.
NOVA development will continue but only the [userscript](https://openuserjs.org/scripts/rainart/Nova_YouTube) version
In developer's name missed 'g' letter.
https://openuserjs.org/scripts/raingart/Nova_YouTube

**Comment by raingart** [comment]
oh thanks
