### ISSUE TITLE
[Bug] options.js 404

### ISSUE THREAD

**Issue by muescha** [raingart/Nova-YouTube-extension#185]
# Setup
 - Browser: Chrome 127.0.6533.99 
 - Tampermonkey 5.1.1
 - Nova 0.50.0 

# Problem

- I am on the options page ( https://raingart.github.io/options.html )
- in the console I found this error:

![Bildschirmfoto 2024-08-09 um 19 36 31](https://github.com/user-attachments/assets/8c74a5b1-e982-45b1-aa47-4250a1761142)

But interesting: there is somehow an different `options.js` laying around:

![Bildschirmfoto 2024-08-09 um 19 36 42](https://github.com/user-attachments/assets/4354af09-685c-4765-b363-497ea7df3f03)

in the github page repo there is no `options.js` file avaiable.

**Comment by LanGsA0** [comment]
Options page is not working.

**Comment by raingart** [comment]
@LanGsA0 now fixed
