### ISSUE TITLE
Options page doesn't open

### ISSUE THREAD

**Issue by Kodapegir** [raingart/Nova-YouTube-extension#19]
Vivaldi + Tampermonkey + Nova. When I click on the "Nova settings" icon in Youtube I see only Raingart animation. From [options.html](https://raingart.github.io/options.html?tabs=tab-plugins) page redirects me to main page.
I've tried Violentmonkey + Nova script, no luck.
Chrome + Tampermonkey + Nova script do the same.
Chrome is clean installed without any other plugins and scripts. 
Windows 11.

**Comment by raingart** [comment]
Try changing your browser language to english

**Comment by Kodapegir** [comment]
In a developer's console I see
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
three.min.js:formatted:3530 THREE.WebGLRenderer 85dev
I don't know is it an issue.

**Comment by Kodapegir** [comment]
> Try changing your browser language to english

Yes, it works in Chrome, but not in Vivaldi.

**Comment by raingart** [comment]
> In a developer's console I see Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'. three.min.js:formatted:3530 THREE.WebGLRenderer 85dev I don't know is it an issue.

The browser is complaining because it's not letting the browser fingerprint you.

FLoC (Permissions-Policy) - Google’s FLoC is an attempt to track users even when their browsers (rightly) block third-party cookies

[more](https://seirdy.one/posts/2021/04/16/permissions-policy-floc-misinfo/)
