### ISSUE TITLE
[Bug] Nothing is working

### ISSUE THREAD

**Issue by alexander-paterson** [raingart/Nova-YouTube-extension#196]
The options page appears to be broken, the dropdowns in the plugin page are all expanded. I can't save any changes made to anything, as it looks like the error validation is stopping it.

 - Browser: Firefox 133.0.3
 - Violentmonkeyv2.29.0
 - Nova 0.50.0.1

![image](https://github.com/user-attachments/assets/13a43d47-81b1-4e89-954d-5ba617636948)

**Comment by raingart** [comment]
try [dev](https://gist.github.com/raingart/d734dd35f7090e9824df15f52c36f8a0) ver

**Comment by raingart** [comment]
I fixed  in the regular ver
