### ISSUE TITLE
Picture-in-Picture settings

### ISSUE THREAD

**Issue by alkaris2** [raingart/Nova-YouTube-extension#20]
Any chance you can add settings for Picture-in-Picture stuff, like setting default window size and default window placement when it opens? Even if it's just a setting that remembers the last size it was opened and set to and where the last position the window was opened.

**Comment by raingart** [comment]
No! At the js level, there are no corresponding APIs to control the corresponding parameters.

Try "Pin player while scrolling". This is an example of the only thing that is available

**Comment by alkaris2** [comment]
Pinning player isn't exactly what's useful, but alright. Shouldn't have to rely on specific API to control it but in Javascript it should be extensible in functionality.

**Comment by raingart** [comment]
Here is the documentation:
https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API
if you find anything useful please let me know.

And СSS does not work, at least for me,
https://developer.mozilla.org/en-US/docs/Web/CSS/:picture-in-picture
 I checked.

Or you can look for other solutions. And if there is a functionality present, send it to me, i will check
