### ISSUE TITLE
The function of adding an RSS feed - wrong feed address

### ISSUE THREAD

**Issue by jojoPL1987** [raingart/Nova-YouTube-extension#21]
The function of adding an RSS feed always (in all YouTube channels) gives the following address:
`https://www.youtube.com/feeds/videos.xml?channel_id=[object%20Promise]`
and the YouTube RSS feed address should look like this:
`https://www.youtube.com/feeds/videos.xml?channel_id=UChf0Knt-e9Pw8VywfuTZCjA`

 - Vivaldi 5.4.2753.51 (stable)
 - Violentmonkey 2.13.1 (stable)
 - Nova version: 0.32.9

**Comment by raingart** [comment]
Fixed
Check [beta ver](https://openuserjs.org/scripts/raingart/Nova_YouTube)
