### ISSUE TITLE
Autopause on tab focus loose

### ISSUE THREAD

**Issue by PF4Public** [raingart/Nova-YouTube-extension#24]
Would it be possible to pause on tab focus loose?

**Comment by raingart** [comment]
"Autopause all background tabs except the active one" - there is a similar plugin.

Yes, I will do what you want. I will notify you when this functionality becomes available.

**Comment by PF4Public** [comment]
It is indeed similar, but it does not cover the situation where one switches to non-youtube tab. I also wonder if focus loose triggers upon mouse leave from the browser window to another window. By any chance do you know if that's the case?

Thanks!

**Comment by raingart** [comment]
You can see for yourself. Replace:
```
// window.addEventListener('blur', pause);
```
with:
```
window.addEventListener('blur', function () {
  video.pause();
});
```
and turn on
"Autoplay on tab focus"

**Comment by PF4Public** [comment]
> ```
> window.addEventListener('blur', function () {
>   video.pause();
> });
> ```
> 
> 
>     
>   
> 
> and turn on
> "Autoplay on tab focus"

It works! Video got paused both by leaving the tab as well as by leaving the browser window. There is also a side effect that interacting with browser window (opening extensions menu, window menu etc.) pauses the video, therefore it would be useful to have an option for pausing specifically as some people might find this behavior disturbing.

**Comment by raingart** [comment]
Enable new option 
"Autopause video if tab loses focus" 
in new [ver 0.3.11](https://openuserjs.org/scripts/raingart/Nova_YouTube)

**Comment by BobbyWibowo** [comment]
> [ver 0.3.11](https://openuserjs.org/scripts/raingart/Nova_YouTube)

Isn't the version string supposed to be `0.32.11`?
I suspect my Violentmonkey is not recognizing it as an update because `0.3.11` is less than `0.32.10` (last version)

**Comment by raingart** [comment]
Thank you, fixed
now - Version: 0.32.11+d18513b updated 1s ago

**Comment by raingart** [comment]
I forgot to mention for you that I "solved" the problem with the player stopping when calling the menu etc.
But this "solution" leads to the fact that when calling the chain:
`loss of tab focus (but the tab is active)` > `switching to another tab` - then the video may not pause.

**Comment by PF4Public** [comment]
> `loss of tab focus (but the tab is active)` > `switching to another tab` - then the video may not pause.

And it also does not pause if leaving the window :-\

**Comment by raingart** [comment]
i.e. is it better to leave the old behavior?

**Comment by raingart** [comment]
from code section:
https://openuserjs.org/scripts/raingart/Nova_YouTube/source#H46818339fea2a56375454e8ada79695f31f376bbfdf862dc201f0e2ddaaee78510295fb094824cffd4386053e8d11b2889885e8ebaa267aa7026b8f45b134f35L3845

If you know js you can try to change

**Comment by PF4Public** [comment]
I cannot say for everyone, but for me it would be ideal if video got paused if I leave the tab or browser window. I rarely interact with window menu, so that would not bother me.

Of-course one could edit userscript, I could totally write 
```js
window.addEventListener('blur', function () {
  video.pause();
});
```
The problem is that upon update all changes are lost :)

**Comment by raingart** [comment]
ok i reverted the changes.

**Comment by PF4Public** [comment]
So do you plan implementing this as an option or not? I'm confused.

**Comment by raingart** [comment]
Yes. I'll leave the old one.
The 2th ver that I implemented will be comment.
There was just another issue and I will add it to the new release.

it turns out openuserjs is used as a beta version.
greasyfork seems to be stable. Because you can't change the published version there

and I delete the message and leave only those that are important.

**Comment by raingart** [comment]
all is ready
