### ISSUE TITLE
API Key not working

### ISSUE THREAD

**Issue by lugohtk** [raingart/Nova-YouTube-extension#25]
![image](https://user-images.githubusercontent.com/112210418/195955286-7567abd1-47dc-4b93-8995-b4fdf40cbd69.png)

when I try to put the API Key it says that the requested format is not, copy the api key alone and copy it as google says (key=API_KEY)

**Comment by raingart** [comment]
Here is the instruction - https://gist.github.com/raingart/080d09ae4070a8f4f892a93b0075729f

Pay attention to the last photo. What is the format of the key. 

You can email me the key you generated. If its format is different what would I update the mask to check for validity

**Comment by lugohtk** [comment]
idk why it doesn't work, create 3 different keys until it worked. thx, good extension:)

**Comment by raingart** [comment]
https://github.com/raingart/Nova-YouTube-extension/blob/master/html/options.html#L120

the mask checks the key only by the first characters "AIzaSy.." and then what will be the numbers and letters "[\d\w]+"

send me an email (raingart@protonmail.com) or here (I will delete message) those keys that were before. To find out why they didn't fit

**Comment by Coldblackice** [comment]
> Here is the instruction - https://gist.github.com/raingart/080d09ae4070a8f4f892a93b0075729f
> 
> Pay attention to the last photo. What is the format of the key.
> 
> You can email me the key you generated. If its format is different what would I update the mask to check for validity

The issue is with the settings page's mask pattern, which accepts only digits and word-chars. However, Google is generating API keys containing a "-" dash/minus character in them (it just happened with mine), and "-" isn't included with \w, only the underscore is.

**Comment by raingart** [comment]
fixed
