### ISSUE TITLE
Ignore live streams option for "Video auto pause" plugin

### ISSUE THREAD

**Issue by BobbyWibowo** [raingart/Nova-YouTube-extension#26]
Hi there!
![image](https://i.fiery.me/bgPO.png)
As the title says, can we have an option to ignore live streams for this plugin?
Specifically actual live streams which are still LIVE, not archived ones

**Comment by raingart** [comment]
The only difference in the html code is the title in the time block:
```Streamed N days/ hours ago```

But the word "Streamed" depends on the specified language. I can't take into account all the languages ​​users use.

It is possible to get information in API requests. But this is not the optimal solution.

**Comment by raingart** [comment]
I see you are from Indonesia. Do you have free time to correct the translation? Because she is a photo you use English probably because the translation is too bad

**Comment by BobbyWibowo** [comment]
> Because she is a photo you use English probably because the translation is too bad

Ah, no, my browser is on English language, so it is as intended

I only browse the internet on English basically, so translations don't really concern me

---

> The only difference in the html code is the title in the time block: `Streamed N days/ hours ago`
> 
> But the word "Streamed" depends on the specified language. I can't take into account all the languages ​​users use.
> 
> It is possible to get information in API requests. But this is not the optimal solution.

Ah, I was referring to currently LIVE streams, so the phrase to match should be `Started streaming N ago`:

![image](https://i.fiery.me/r2cV.png)

And if string matching can get the job done, even if not the most effective across all UI languages, I personally will not mind

**Comment by raingart** [comment]
Sorry, I'm dumb today.
I added what you want
try version [0.32.11.1](https://openuserjs.org/scripts/raingart/Nova_YouTube)
 
new code:
https://openuserjs.org/scripts/raingart/Nova_YouTube/source#H46818339fea2a56375454e8ada79695f31f376bbfdf862dc201f0e2ddaaee78510295fb094824cffd4386053e8d11b2889885e8ebaa267aa7026b8f45b134f35L5658

**Comment by BobbyWibowo** [comment]
I can confirm it works as desired, thank you!

**Comment by raingart** [comment]
When testing, a conflict was found inside the plugin. To activate update and enable 
`Ignore live`

Option not compatible with `Apply to video = "embed"`
 earlier name `Only for embedded videos`

**Comment by BobbyWibowo** [comment]
Duly noted, thanks again for hard work thus far!
