### ISSUE TITLE
"Attention! Nova The page will automatically within 5 sec CliCk to cancel"

### ISSUE THREAD

**Issue by fourteen-1** [raingart/Nova-YouTube-extension#27]
*Describe the bug*

![image](https://user-images.githubusercontent.com/73333396/198830226-ffda9e72-3627-41a4-aae5-aba6c0839651.png)

1. Playlists get the message "Attention! Nova The page will automatically within 5 sec CliCk to cancel" every 5-7 seconds.
2. Reloads the page (unless cancelled manually)
3. Repeats Step 1.

Stuck in this loop. Not sure which enabled option is causing this.

 - Browser: Firefox 106.0.2 (64-bit) on Windows 10 21H2
 - ...monkey [ex: violentmonkey 2.13.3]
 - Nova version: 0.32.11 (latest)

**Comment by raingart** [comment]
I disabled this function.
Try this ver. https://openuserjs.org/scripts/rainart/Nova_YouTube

>Why is it needed?

Because of the introduction of Nova on the youtube page, unnecessary information accumulates. It can lead to slowdowns. The principle of the described functionality is that after 30 page transitionend (in the playlist), it tries to reload the page in order to reset the js cache.

>every 5-7 seconds
It should not be. I'll disable it. Let the user manually reboot if necessary.

**Comment by fourteen-1** [comment]
It's not doing the thing any more. Thank you for fixing it.

> Because of the introduction of Nova on the youtube page, unnecessary information accumulates. It can lead to slowdowns. The principle of the described functionality is that after 30 page transitionend (in the playlist), it tries to reload the page in order to reset the js cache.

To give you a little more context: the playlist in question had 66 videos and I clicked on the 48th video. The bug kept repeating on this 48th video where it would continue to reload the 48th video upon playing the video for about 5-7 seconds.

**Comment by raingart** [comment]
thanks for clarifying the context

**Comment by fourteen-1** [comment]
New issue: the next video in the playlist doesn't load. After finishing the current video, it just stays in that video (paused) and doesn't move on to the next video in the playlist.

**Comment by raingart** [comment]
I'm missing data. Namely settings and url. Without them, 

I can suggest that we try in one of the plugins:
- Playlist autoplay control button
- Stop video preload
- Video auto pause
- Autopause video if tab loses focus (in Autopause all background tabs except the active one)
- Add playlist reverse order button

**Comment by raingart** [comment]
Tou can change the settings and send a link to the video
it is also possible there is a conflict with another script

**Comment by raingart** [comment]
and you can also send an error message in the console tab
