### ISSUE TITLE
"Player sensitivity visibility range" not work

### ISSUE THREAD

**Issue by cmhrky** [raingart/Nova-YouTube-extension#28]
*Describe the bug*

Whatever the "Pin player while scrolling > Player sensitivity visibility range" setting is set, it becomes active when the page is scrolled a little bit. My goal is for the player to activate when half of it is not visible but I failed.

 - Browser: Chrome 107.0.5304.88
 - Violentmonkey 2.13.3
 - Nova version: 1.33.0

**Comment by raingart** [comment]
When implementing, I tested it, but I also didn’t understand whether it works or not. I didn't see any difference when changing the value. I came to the conclusion that this is my misperception. The documentation can't be wrong.

[Here](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) is the documentation (threshold parameter)

My [implementation](https://github.com/raingart/Nova-YouTube-extension/blob/f73c457ff5c53e48ca8617355a4d4a21aac692ea/plugins/player/pin.js#L116)

In the next release i will just hide this parameter

**Comment by cmhrky** [comment]
I wish Nova had this feature.
