### ISSUE TITLE
End cards improvements

### ISSUE THREAD

**Issue by cmhrky** [raingart/Nova-YouTube-extension#29]
Can "End cards" be hidden when the mouse is automatically hidden over the player?
Can the end cards be made visible when we move the mouse?

**Comment by raingart** [comment]
if such an implementation satisfies you
`#movie_player:not(:hover) > [class^="ytp-ce-"]`

then I can replace the current one

**Comment by raingart** [comment]
check [beta version](https://openuserjs.org/scripts/raingart/Nova_YouTube)

**Comment by cmhrky** [comment]
Thanks. I think that should be added as well.

`.ytp-autohide > [class^="ytp-ce-"]`
