### ISSUE TITLE
[Feature] Improved "Save-to-Playlist" functionality

### ISSUE THREAD

**Issue by Coldblackice** [raingart/Nova-YouTube-extension#33]
Regarding Youtube's "Save to playlist" function, would it be possible to add options for:

1.) An increased height/length of the "Save to playlist" popup, given its currently compressed length, necessitating lots of scrolling to find a particular playlist. It also doesn't help that Youtube's CSS for the playlist is very clunky and spread out between playlists.

2.) Or even better, a searchbox embedded in the "Save to Playlist" popup: when text is entered into the box, it does a "live" quick-filtering of playlists containing that amount of text. When the box is cleared, all playlists show.

**Comment by raingart** [comment]
1. ![Screenshot from 2022-11-11 12-19-13](https://user-images.githubusercontent.com/13064767/201319667-e03acb12-d753-4a27-906f-aad1eb8a04d4.png) 
Never used this functionality. But judging by the styles it is enough to add css:
```
ytd-add-to-playlist-renderer[dialog] #playlists.ytd-add-to-playlist-renderer {
    max-width: max-content !important;
}
```

2.  https://greasyfork.org/en/scripts/436123-youtube-save-to-playlist-filter - I'm unsure work now. Write if not. I will try to fix it

**Comment by raingart** [comment]
I remembered that you had previously strongly suggested the bottom changes in greasyfork.

Therefore, in the next release, I add the "Save to playlist menu sort" plugin:

![Screenshot from 2022-11-25 15-26-34](https://user-images.githubusercontent.com/13064767/203995967-b1d0b0c3-2a8d-4dde-a078-c9ec09e2bc4f.png)

![Screenshot from 2022-11-25 15-26-49](https://user-images.githubusercontent.com/13064767/203995965-9aa1b832-add4-4b13-8f4f-5eb552734e1e.png)
