### ISSUE TITLE
[Feature] Better Comment Sorting

### ISSUE THREAD

**Issue by Coldblackice** [raingart/Nova-YouTube-extension#37]
A function for comment-sorting (better than Youtube's sorting) would be phenomenal. 

Namely, the ability to sort **all** comments by:
-  _most-upvotes_
- _most-replies-to_
- _newest/oldest_
- _comments-that-creator-replied-to_

The two most useful sortings would be by _most-upvotes_ and _newest_ vs. _oldest_.

Currently, Youtube's comment-sorting is algorithmically selective, Youtube choosing from a pool of comments to present as "Top Comments". Even then, Youtube doesn't sort them in proper order. Even worse, you're not actually seeing the highest upvoted comments of all, but rather, Youtube's "digest" of picked recent comments with upvotes. 

It would be great to be able to see an absolute scale of comment sorting from highest-to-lowest across _all_ comments.

**Comment by raingart** [comment]
I'll think about it. But I doubt it. Since the Youtube API has a limit on the number of calls per unit of time

**Comment by Coldblackice** [comment]
Makes sense. Even just 1-2 extra "Load more"s (then sorted), would be useful. Just an idea.

**Comment by raingart** [comment]
Test version (extension). This is an example of the functionality that will be available
Loads only the top 100 (by Google comment versions) possible by date but not yet implemented

[nova-extensions_v1.34.0.zip](https://github.com/raingart/Nova-YouTube-extension/files/10219183/nova-extensions_v1.34.0.zip)

Here is the full list of available data in the comment
```
{
      "snippet": {
         "videoId": "aabbcc11",
         "textDisplay": "text",
         "textOriginal": "text",
         "authorDisplayName": "user A",
         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/..",
         "authorChannelUrl": "http://www.youtube.com/channel/UC1..",
         "authorChannelId": { "value": "UC.." },
         "canRate": true,
         "viewerRating": "none",
         "likeCount": 5,
         "publishedAt": "2022-01-01T01:23:00Z",
         "updatedAt": "2022-01-01T01:23:00Z"
      },
   "canReply": true,
   "totalReplyCount": 7,
   "isPublic": true
}
```
p.s. may need your api key

**Comment by raingart** [comment]
Here is the pre-release version.
[nova-extensions_v1.34.0.zip](https://github.com/raingart/Nova-YouTube-extension/files/10298422/nova-extensions_v1.34.0.zip)

Missing reply view totaly. But the left link to the comment.
