### ISSUE TITLE
[Bug] Infinite refresh page "videos"

### ISSUE THREAD

**Issue by jojoPL1987** [raingart/Nova-YouTube-extension#44]
I have an error if I enable this option:
Plugins >> Other >> Default tab on channel page
and "videos" + "redirect"

Now if I go from any video to the author's channel, e.g. from:
https://www.youtube.com/watch?v=f8hT3oDDf6c

Then I go straight to the "videos" subpage, but I have this transition one after the other. So first I see in the address bar:
`https://www.youtube.com/channel/UCK9X9JACEsonjbqaewUtICA/videos/`
after:
`https://www.youtube.com/channel/UCK9X9JACEsonjbqaewUtICA/videos/videos/`
after:
`https://www.youtube.com/channel/UCK9X9JACEsonjbqaewUtICA/videos/videos/videos/`
after:
`https://www.youtube.com/channel/UCK9X9JACEsonjbqaewUtICA/videos/videos/videos/videos/`

And so on and on. So using this option, the "videos" subpage becomes useless.

And if the error does not occur immediately after going to the "videos" subpage, it already occurs if you use the search engine on this subpage and enter something in it and press enter.

 - Browser: Opera 94.0.4606.38 or Vivaldi 5.6.2867.50
 - Violentmonkey 2.13.5 (in Opera and Vivaldi)
 - Nova version: 0.35.1 (in Opera and Vivaldi)

**Comment by raingart** [comment]
try [beta](https://openuserjs.org/scripts/raingart/Nova_YouTube) ver.

**Comment by jojoPL1987** [comment]
From the first tests it turns out that the error is no longer there. In both cases. I tested in Vivaldi.
