### ISSUE TITLE
[Bug] Can't choose resolution in full screen mode with Custom buttons quick-quality

### ISSUE THREAD

**Issue by Pi3truch** [raingart/Nova-YouTube-extension#47]
First of all thanks for Nova YT, great stuff.

I have a problem to choose resolution in full screen mode. The resolutions list disappear when I move cursor above the button.
Sometimes, when I move mouse very quick I can reach th resolution list, but it's difficult.

 - Browser: Opera 94.0.4606.76 | Chromium:108.0.5359.125 
 - violentmonkey 2.13.9 
 - Nova Version: 0.36.0.1

**Comment by raingart** [comment]
check in [beta ver](https://openuserjs.org/scripts/raingart/Nova_YouTube)

**Comment by Pi3truch** [comment]
It works!

**Comment by raingart** [comment]
cool

**Comment by Pi3truch** [comment]
I discovered that it's not working with embedded videos.

**Comment by raingart** [comment]
[Ah shit, here we go again](https://www.youtube.com/watch?v=KOaeDHeJ80I)
try updating and checking now

**Comment by Pi3truch** [comment]
What a quick response!
Now it also works in embeded full screen. Thanks.
