### ISSUE TITLE
[Bug] Header unfixed makes one scrollbar does not appear

### ISSUE THREAD

**Issue by robertgarciakof** [raingart/Nova-YouTube-extension#48]
When "Header unfixed" is enabled in Nova, the menu of the three horizontal lines located in the upper left corner of YouTube does not show the vertical scroll bar that appears by default when you hover the mouse over any option in that menu

 - Browser: Chrome
 - Nova version: 1.36.1

**Comment by raingart** [comment]
I checked inChromium 109.0.5414.120 (Official Build) (64-bit)

Scroll is displayed on hover:
![Screenshot_18](https://user-images.githubusercontent.com/13064767/216528083-90ebb0e8-419d-47f1-904c-96a097830fcd.png)

 Try disabling other scripts, extensions and style modifiers.

**Comment by robertgarciakof** [comment]
I am testing it now with the same version of Chromium as you to do the test only with the Nova extension and without having logged in YouTube, and in Subscriptions the scroll bar is shown as in your screenshot, but there are other menus like Home, Explore (Trending, Music...) or being logged in where there is no scroll bar

**Comment by raingart** [comment]
Yep, I saw it, thanks. I have never explored this far on Trending and other dumps.

I will check the beta

**Comment by raingart** [comment]
Did you check it fixed?

**Comment by robertgarciakof** [comment]
As you wrote I will check the beta, I thought it in the beta wasn't fixed yet.
I am testing now the latest beta 0.36.1.7 and it is solved

**Comment by raingart** [comment]
fixes get into beta immediately after I see and fix the bug.
I would keep only one rolling version of OpenUserJS. But alas, the site itself is not stable.
