### ISSUE TITLE
[Bug] Header compact problem when get out full screen

### ISSUE THREAD

**Issue by robertgarciakof** [raingart/Nova-YouTube-extension#49]
If "header compact" is enabled in Nova and I open a video, the header is displayed correctly in compact mode, but when I put the video to full screen and then I get out full screen, a horizontal black part appears at the bottom of the header.

 - Browser: Chrome 109.0.5414.120
 - Nova version: 1.36.1

**Comment by raingart** [comment]
check [beta ver](https://openuserjs.org/scripts/raingart/Nova_YouTube)

**Comment by robertgarciakof** [comment]
Ok, fixed in beta ver
