### ISSUE TITLE
[Bug] Doesn't save option Volume - hotkey - disable

### ISSUE THREAD

**Issue by robertgarciakof** [raingart/Nova-YouTube-extension#51]
In the Nova options, in "Volume" - "Hotkey" I select "disable" from the drop-down menu and I press Save, but when I close and enter in the options again, has not been saved because there is selected other option that was previously instead of "disable"

 - Browser: Chrome and Chromium 109.0.5414.120
 - Nova version: 1.36.2

**Comment by raingart** [comment]
The data is saved correctly.
An error occurred in the form data filling function.

I'll fix it in the next release

**Comment by raingart** [comment]
check oprions page

**Comment by robertgarciakof** [comment]
Solved
