### ISSUE TITLE
[Feature] Stop jumping to next video

### ISSUE THREAD

**Issue by Fred-Vatin** [raingart/Nova-YouTube-extension#52]
Hi,

At the end of a playlist, when the last item is played, YT opens a random video. It happens also when you play any other video. At the end, YT open a new video while you’re reading comment for instance. But I want videos on playlists keep auto-playing.

I hope there was an option to prevent that.

**Comment by raingart** [comment]
You tried use "Add playlist autoplay control button"?

in the test playlist everything is ok - if disable button above
https://www.youtube.com/watch?v=-mY7zepLQAU&list=PLv2T6hXHdnHRbQdOxWhod0U_VYy33T_qK&index=1

**Comment by raingart** [comment]
And you want to stop playback at the end of the playlite. I'm sorry I didn't understand right away. I'm not sure. 
I will check

**Comment by Fred-Vatin** [comment]
> Try turning this switch off. ![Screenshot_1](https://user-images.githubusercontent.com/13064767/217597575-b4b34e32-541b-4f0a-90f7-06b3da88b80b.png)

Thanks. This works with video outside playlist but if you’re reaching the end of the last video of a playlist, YT keeps opening a new video nonetheless. Unless this 
![image](https://user-images.githubusercontent.com/22337329/217610005-c88ee425-816b-4d83-9369-53dc730bd47c.png)
is disabled but the drawback is it turns off auto-play for all videos of the playlist.

**Comment by raingart** [comment]
try this playlist
https://www.youtube.com/watch?v=-mY7zepLQAU&list=PLv2T6hXHdnHRbQdOxWhod0U_VYy33T_qK&index=1

I don't have this behavior.
try disabling other scripts and extensions

[video example](https://user-images.githubusercontent.com/13064767/217613549-badc8509-c686-447d-817a-e1280da6a58c.mp4)

**Comment by Fred-Vatin** [comment]
It seems that I have no issue with this playlist. After having run some tests, my theory is when playlist contains the message “_**X unavailable videos are hidden**_” the bug happens. Unfortunately, the hidden videos can not be removed from a playlist as far as I know.

Example : https://youtube.com/playlist?list=PLi41SR40-ufgioseqSs1YZpFGGhXPEFIc

**Comment by raingart** [comment]
I wrote a function that blocked playback if the last element of the playlist was not available. But he didn't.
Can be deleted if the video is in its own playlist
https://www.youtube.com/watch?v=8VNB1f-CnYA

if you enter this code into the console, you will see the internal structure of the playlists. It can be edited but not always successful.
`document.querySelector('ytd-watch, ytd-watch-flexy')?.data.contents?.twoColumnWatchNextResults.playlist.playlist`

**Comment by Fred-Vatin** [comment]
I think this can be closed unless a feature to handle this use case is planned.

**Comment by raingart** [comment]
I will try to make either a message that the video is not available and it is recommended to delete it. Or turn off playback. It's not hard to implement.

It's good if the playlist is yours. What if he's an outsider? Here is an example, then this is the problem
https://www.youtube.com/watch?v=v0PqdzLdFSk&list=OLAK5uy_m-Dv_8xLBZNZeysu7yXsw7psMf48nJ7tw&index=8

**Comment by raingart** [comment]
I will report back to you when I fix it.

**Comment by Fred-Vatin** [comment]
> I will try to make either a message that the video is not available and it is recommended to delete it. Or turn off playback. It's not hard to implement.
> 
> It's good if the playlist is yours. What if he's an outsider? Here is an example, then this is the problem https://www.youtube.com/watch?v=v0PqdzLdFSk&list=OLAK5uy_m-Dv_8xLBZNZeysu7yXsw7psMf48nJ7tw&index=8

Good point !

**Comment by raingart** [comment]
I added a check to the "Add playlist autoplay control button" part of the plugin

check [beta var](https://openuserjs.org/scripts/rainart/Nova_YouTube)

So far I haven't thought of a better implementation. Perhaps you should specify that user can remove the video from the playlist. But in the built-in alert() there is no way to insert active links
