### ISSUE TITLE
[Bug] Header unfixed causes scroll to top

### ISSUE THREAD

**Issue by robertgarciakof** [raingart/Nova-YouTube-extension#53]
With only the Header unfixed option enabled, I open a video and wait a few seconds for the page to load, then I press Av Pag on the keyboard or roll the mouse wheel down to quickly scroll down to the comments section and the problem is that the screen automatically scroll to the top of the page at the time it should show the comments

 - Browser: Chrome 109.0.5414.120
 -  Violentmonkey 2.13.9
 - Nova version: 1.36.2 or beta 0.36.2.2

**Comment by raingart** [comment]
It's not exactly a bug. This is a feature of the "Scroll after header" function
It is launched after the auto-scroll trigger fires inside YouTube itself. It is not initially designed for the fact that the Header will not be fixed. These are fixes over fixing youtube itself.
I added a check in the beta that if the Header is in the viewport, then only the activation.
Perhaps this will help.

![Screenshot from 2023-02-09 15-24-50](https://user-images.githubusercontent.com/13064767/217826323-9d2611b0-678e-4e7e-9b81-7b8e9fa722e1.png)

**Comment by robertgarciakof** [comment]
Good, what you've changed fixed that behavior.

About your comment, I had already noticed before that on YouTube without Nova it also happened but only if you just open the video and then scroll down to the comments without waiting for the page to load, but I published it as a bug because with Nova it happens in all cases (with the page already loaded or with the page loading)

**Comment by raingart** [comment]
I confess I always thought that I was writing shitty code. And Nova is an example of this.
But watching various bugs over the years has shown that Youtube is written as shitty as Nova.

I always thought that super high quality programmers work at Google. And all sorts of scripts like me are any rabble or students.

But my other projects that are hosted on google servers keep reporting internal crashes more and more often. About 2 times a week.
It seems to me that the level of support over the past 2 years has greatly decreased.

And the balance of such projects as Nova is kept in balance between two extremes - "I'm tired and don't want to spend more time on this project" and "and I'm not going to put up with perfidious not usable someting"


 
here are the errors from the last month
![Screenshot from 2023-02-09 17-01-59](https://user-images.githubusercontent.com/13064767/217849902-060c1d58-f55a-4b9b-b704-1fae9987b00e.png)
![Screenshot from 2023-02-09 17-01-34](https://user-images.githubusercontent.com/13064767/217849940-0f4f664d-11ed-413f-99c4-8580e71e29f2.png)
![Screenshot from 2023-02-09 17-02-27](https://user-images.githubusercontent.com/13064767/217849885-399728a1-44d1-45e6-9c45-9b4ebf36a8a6.png)
