### ISSUE TITLE
[Bug] Header Bar crops top of videos

### ISSUE THREAD

**Issue by alkaris2** [raingart/Nova-YouTube-extension#54]
YouTube has made some changes to their layouts and the top bar with the Search and everything now crops the top of videos. An option to "fix" said issue would be to add compact the `#background.ytd-masthead` section from 56px to 36px.

 - Browser: Vivaldi 5.6.2867.50
 - Violent Monkey 2.13.9.3
 - Nova version: 0.36.2

**Comment by raingart** [comment]
[Fixed](https://openuserjs.org/scripts/raingart/Nova_YouTube). 
It is noteworthy that the bug appears in new ver of browsers. Some css parameter seems to be missing in older versions.
