### ISSUE TITLE
[Feature] Make buttons without labels round

### ISSUE THREAD

**Issue by Sam-Oak** [raingart/Nova-YouTube-extension#56]
…to look more native. i use this CSS:
```
.ytd-menu-renderer[button-renderer=""] .cbox {
    display: none;
}
.ytd-menu-renderer[button-renderer=""] .yt-spec-button-shape-next__icon {
    margin-inline: -10px !important;
}
```
![round buttons without labels](https://user-images.githubusercontent.com/62823895/220490801-58badf67-3adf-4ec5-885d-bc00864ee976.png)

**Comment by raingart** [comment]
check [beta](https://openuserjs.org/scripts/raingart/Nova_YouTube)

I used your example but implemented it differently. Compare it
