### ISSUE TITLE
bug in rotate

### ISSUE THREAD

**Issue by trickertech** [raingart/Nova-YouTube-extension#62]
1.39.0 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

there is a bug in rotate it does not work completely it just puts it aside once and stops, only in version 1.36 it was working perfectly.

**Comment by raingart** [comment]
fixed
this error was [in regex](https://github.com/raingart/Nova-YouTube-extension/commit/616847ae44daf83cf72996d0049ba47cdde20a48#diff-6252749e846f437ca6ae9bc91c89d41592f408398d3595834ea3a9459d596393L429)
