### ISSUE TITLE
[Bug] Addon constantly deletes itself

### ISSUE THREAD

**Issue by nulledone** [raingart/Nova-YouTube-extension#64]
*Describe the bug*

 - Browser: Firefox 111 
 - Violentmonkey 2.14 
 - Nova 0.39.1 

After a week or so, the script just deletes itself only first few lines of the code (comments and metadata) remains.

**Comment by raingart** [comment]
This is not a problem with Nova but with openuserjs.org
read more https://github.com/raingart/Nova-YouTube-extension/issues/58

Most likely you just need to remove the openuserjs repository. I thought that if you specify the update and download paths to another source (greasyfork). I thought that would solve the problem. Probably no
