### ISSUE TITLE
[Bug] Featured video titles are almost always wrong after watching few videos

### ISSUE THREAD

**Issue by nulledone** [raingart/Nova-YouTube-extension#65]
*Describe the bug*

 - Browser: Firefox 111 
 - Violentmonkey 2.14 
 - Nova 0.39.1 

When I hover over to click them I can see the real title
![image](https://user-images.githubusercontent.com/29547468/226101983-a795e15a-2c3e-4a86-b939-0bd549570860.png)

**Comment by raingart** [comment]
try disable "Decapitalize thumbnails title"

**Comment by nulledone** [comment]
Disabled it, will report in after some time. Thanks for your quick reply.

**Comment by nulledone** [comment]
![image](https://user-images.githubusercontent.com/29547468/226616440-10a0fa0a-8bc3-4b3d-b1ba-358307ff2316.png)
Seems to be still same sadly. Anything else should I try?

**Comment by raingart** [comment]
Try to disable these 2:
![Screenshot_1](https://user-images.githubusercontent.com/13064767/226617117-ce86c7f3-5950-474e-9ea2-2a713c2970ac.png)
 If that doesn't work, disable Nova.

**Comment by nulledone** [comment]
Both are already disabled, no issue when Nova is not enabled.

**Comment by nulledone** [comment]
Some other observations;
It does not happen if I hop between videos fast, but when I finish a video and watch next one it happens randomly.
It does not happen if I open every new video on a new tab.

**Comment by raingart** [comment]
Try iterating by disabling plugins and find out what affects it.

I advise you to start with those that are called "thumbs"

**Comment by nulledone** [comment]
I think disabling the mark watched option seems to have fixed it, but will report if issue persists. Thanks for the troubleshooting.
