### ISSUE TITLE
Updated Ukrainian 19.03.2023 [Feature]

### ISSUE THREAD

**Issue by bmkuma** [raingart/Nova-YouTube-extension#66]
Translated some strings
[Nova-YouTube-extension-masterUA_Lang_update_19.03.2023.zip](https://github.com/raingart/Nova-YouTube-extension/files/11011203/Nova-YouTube-extension-masterUA_Lang_update_19.03.2023.zip)

**Comment by raingart** [comment]
Can you translate these phrases:

- [video-quality]
  - "Diff quality for music in playlists"

- [player-control-autohide]
  -  Hover container

- [header-unfixed]
  - Hotkey toggle

- [player-quick-buttons]
  - aspect-ratio

- [theater-mode]
  - default
  - cinema
  - full-viewport (auto)
  - full-viewport
  - redirect to embedded

- [player-indicator]
  - text-top
  - bar-top
  - bar-center
  - bar-vertical

**Comment by bmkuma** [comment]
@raingart 
[video-quality] - Translation: **[якість відео]**

- "Diff quality for music in playlists" - Translation: **"Змінити якість музики у списках відтворення"**

[player-control-autohide] - Translation: **[Панель керування програвача]**

- Hover container - Translation: **"Відображати вміст при наведенні"**

[header-unfixed] - Translation: **[Фіксація шапки сайту]**

- Hotkey toggle - Translation: **"Перемикання гарячою клавішею"**

[player-quick-buttons] - Translation: **[Швидкі кнопки програвача]**

- aspect-ratio - Translation: **"Співвідношення сторін"**

[theater-mode] - Translation: **[Режим кінотеатру]**

- default - Translation: **"За замовчуванням"**
- cinema - Translation: **"Кінотеатр"**
- full-viewport (auto) - Translation:  **"Повноекранний (авто)"**
- full-viewport - Translation: **"Повноекранний"**
- redirect to embedded - Translation: **"Передавати на вбудований"**

[player-indicator] - Translation: **"[індикатор програвача]"**

- text-top - Translation: **"Текст зверху"**
- bar-top - Translation: **"Панель зверху"**
- bar-center - Translation:  **"Панель в центрі"**
- bar-vertical - Translation: **"Вертикальна панель"**
