### ISSUE TITLE
[Bug] pin player issue

### ISSUE THREAD

**Issue by venkat2305** [raingart/Nova-YouTube-extension#69]
*Describe the bug*

https://user-images.githubusercontent.com/55329452/226329435-2737ef69-e7ff-45a8-ab54-d3c4c0ce3bf9.mp4

the video describes the issue. 
after a small movement in the scroll bar, and then when we escape the full screen it minimizes to the pinned player. It shouldn't happen. escaping the full screen should revert to the original state.

 - Browser: edge
tampermonkey, userscript donwnloaded from greasemonkey

**Comment by raingart** [comment]
Try [updated the plugin ver.](https://gist.github.com/raingart/3b7f33353965383f45ec674a33098892) from the unpublished beta ver. To install press "RAW"

UPD: don't forget to disable or replace the current ver.

**Comment by venkat2305** [comment]
im getting 404 not found

**Comment by venkat2305** [comment]
there was an issue and it asked for a google form. I submitted it. Please have a look at it

**Comment by venkat2305** [comment]
it is fixed. Thanks
