### ISSUE TITLE
Userscript version failed to enter settings page

### ISSUE THREAD

**Issue by fhoshino** [raingart/Nova-YouTube-extension#7]
Opening settings page gives all plugin error:
![brave_2022-02-14_03-07-53](https://user-images.githubusercontent.com/771955/153770745-80d0500d-17e7-4e6d-9db7-eef8525400ab.png)

 - Browser [Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit)]
 - Monkey (is use userscript) [violentmonkey 2.13.0]
 - Extension version [e.g. 0.23.0]

**Comment by raingart** [comment]
Seems that the reason is that your ad blocking module perceives this plagin file as an ad and blocks it
Try adding a domain/file to the whitelist

**Comment by raingart** [comment]
The problem was in [link](https://github.com/raingart/raingart.github.io/commit/8b494309f03a65f003baf9f813e8a0cb2ca52483#diff-731851291805f1a0cb31758414a48ba8ce4cde15ae1bb3f58c6f8b9cfe920425L96)
Thanks fixed it
