### ISSUE TITLE
[Feature] hide clip, thanks, download, report 

### ISSUE THREAD

**Issue by venkat2305** [raingart/Nova-YouTube-extension#70]
please give an option to remove the buttons under the player. I use like and dislike, save to playlist options only. it would be great if we could remove all those unnecessary buttons and have the required one only. 
the main request is to remove the ones shown directly under the player and replace that position with useful ones like save to playlist. 
if you know any extension, please share. I found one script but its not working. Also, this would be a nice addition to nova.
thanks.
i want to use nova extensively, please don't get annoyed as I might post a lot feature requests and report bugs.

**Comment by raingart** [comment]
I once met a similar script. But I don't remember where
https://greasyfork.org/en/scripts/440416-youtube-hide-download-and-other-buttons-under-video

https://unhook.app/

**Comment by venkat2305** [comment]
do you plan to add them eventually?

**Comment by venkat2305** [comment]
[this](https://greasyfork.org/en/scripts/440416-youtube-hide-download-and-other-buttons-under-video) script removed those buttons and placed them in the three-dot menu. but we can't configure anything.

**Comment by venkat2305** [comment]
and from unhook extension only these were helpful 
![image](https://user-images.githubusercontent.com/55329452/226395030-6051d9a3-e7e3-439d-9486-09e73fc55fa8.png)

**Comment by venkat2305** [comment]
> An interesting idea is to hide the buttons instead of permanently deleting them

does this take less resources ?

**Comment by raingart** [comment]
v.v. I think there are many more resources.
Just once in a very long time you may need some button. And it is unnecessary to go into the settings that you are off and reload the page. Of course, provided that you have not forgotten that there are such buttons.

Simply hiding css is a much less resource intensive method
`#actions-inner #menu #flexible-item-buttons` - this css points to the buttons container (except likes and dropdown menu)

You wrote that it is difficult to hide certain buttons. Yes and no at the same time. Conventionally, they are divided into 3 groups: 
- likes/dislikes
- Buttons with label 
- And dropdown menu

groups of them are easy to hide if you know css.

**Comment by venkat2305** [comment]
i know basic css and flex box. but it seems pretty complicated. if it is a bit easy for a beginner, can you help me understand it?

**Comment by venkat2305** [comment]
this [script](https://greasyfork.org/en/scripts/447614-youtube-hide-download-clip-and-thanks-buttons) is great. It removes the downoad button and replaces it with the useful save to playlist button. I use only two buttons lke/dislike and save to playlist. the latest yt UI added one step to reach save to playlist(which we use all the time). please have a look into the images. please implement in this way to nova.

Before:
![image](https://user-images.githubusercontent.com/55329452/227139055-ada8958b-33e2-4f35-933c-509dd2a6f0d4.png)

After:
![image](https://user-images.githubusercontent.com/55329452/227138944-23985870-9f6d-4894-aec8-fbf2da49fff9.png)

**Comment by venkat2305** [comment]
please add download, clip, report hide options as well, so that save to playlist comes out of the three dot meny

**Comment by venkat2305** [comment]
i just need save to playlist button under the player. I was trying add ask all the features I use in nova itself. I'm using another [script](https://greasyfork.org/en/scripts/447614-youtube-hide-download-clip-and-thanks-buttons) for this. Thanks for looking into this.

**Comment by raingart** [comment]
I thought a little and made an implementation based on icons. Instead of parsing titles or numbering.

The implementation is not very optimal

**Comment by venkat2305** [comment]
this is perfect
![image](https://user-images.githubusercontent.com/55329452/227444718-4b46bdc3-3b3d-46a2-921e-15f993b61ce7.png)

**Comment by venkat2305** [comment]
please implement for thanks button as well. with that this issue can be closed. Thanks

**Comment by venkat2305** [comment]
https://www.youtube.com/watch?v=b7zBJNmdImo&t=43s
https://www.youtube.com/watch?v=muxq5sQVdlc
https://www.youtube.com/watch?v=Pf8YTpp7B2I
https://www.youtube.com/watch?v=uvNkdAggUGU
https://www.youtube.com/watch?v=Eb7al22iNPc

**Comment by venkat2305** [comment]
Wow.

**Comment by venkat2305** [comment]
this issue is solved. Thanks

**Comment by raingart** [comment]
A new button hide plugin has been merged with "Buttons without labels"

![Screenshot from 2023-03-24 14-50-03](https://user-images.githubusercontent.com/13064767/227526852-bc855a4c-3816-4935-8edd-b30c2ca914fc.png)

Alas, it was not possible to hide three dot meny. The reason is the lack of the ability to determine if there are not hidden items inside
