### ISSUE TITLE
[Feature] hide endscreen suggestions

### ISSUE THREAD

**Issue by venkat2305** [raingart/Nova-YouTube-extension#71]
![image](https://user-images.githubusercontent.com/55329452/226410453-1d665a50-d302-43bb-83e3-0056193a3818.png)

Hide garbage: annotations, endcards option doesn't hide endscreen suggestions. please have a look into this.

**Comment by raingart** [comment]
**endcards** is:
![Screenshot_63](https://user-images.githubusercontent.com/13064767/226411420-5acb6943-9e2c-4c6a-87d9-6f823f7bad66.png)

What you showed is called - **videowall**
![Screenshot_1](https://user-images.githubusercontent.com/13064767/226411780-62631f82-cc9e-4ebd-ba05-4b5fd451bd9c.png)

I see no reason to hide it. It will just be black screen. It does not distract from anything and you can confuse it with a crash or video not loading

I advise you to look at the pictures in spoiler. They show what is hidden.
https://github.com/raingart/Nova-YouTube-extension/wiki/plugins#disable-video-cards

**Comment by raingart** [comment]
Their hiding is not permanent. By user request #29

**Comment by venkat2305** [comment]
the previous extension I used removed those suggestions and it was just a black screen. I guess I was habituated with it. it definitely reduces distraction. if possible please try to add it

**Comment by venkat2305** [comment]
i didn't get what you meant by hiding is not permanent.
with enhacer for youtube, it looks like this 
![image](https://user-images.githubusercontent.com/55329452/226415302-2fd642e1-417a-417d-b89e-d6a6640d20ff.png)

**Comment by venkat2305** [comment]
there's an option in enhancer for youtube which can hide and show endscreen/video wall and cards. we can easily toggle using the custom button on the player. please try to implement the custom button as well. 
this video should explain better.

https://user-images.githubusercontent.com/55329452/227152250-e4c7766e-72fd-4620-adcd-28386eae8dcf.mp4

**Comment by venkat2305** [comment]
with [this](https://github.com/raingart/Nova-YouTube-extension/issues/73#issuecomment-1478158126) and custom buttom which can show/hide endscreens and video cards, I can move to nova completely. thanks

**Comment by venkat2305** [comment]
https://user-images.githubusercontent.com/55329452/227152010-185aa663-ed0a-468e-915e-5333a256b7a4.mp4

**Comment by venkat2305** [comment]
i enabled that option but hovering on the player is showing the cards and endscreen is not hidden. 

https://user-images.githubusercontent.com/55329452/227371680-df96435b-4303-4bbb-8226-422f3d4bc266.mp4

**Comment by raingart** [comment]
Added a button. The animation of switching svg icons took the most time

![Screenshot from 2023-03-26 00-58-52](https://user-images.githubusercontent.com/13064767/227746327-fa7313f1-8be1-461f-b54b-587195dba848.png)

![Screenshot from 2023-03-26 01-01-48](https://user-images.githubusercontent.com/13064767/227746422-dbd7e4f0-c499-44fc-99c9-b5b2b8acbb37.png)

**Comment by venkat2305** [comment]
Can you fix it?

**Comment by venkat2305** [comment]
i can't see the custom button

**Comment by venkat2305** [comment]
i turned off hide buttons/elements set the default card state as show
![image](https://user-images.githubusercontent.com/55329452/227768937-14a63b1b-3ccc-49d7-aef7-db60590516d0.png)
the custom button isn't working at all
[Extensions.webm](https://user-images.githubusercontent.com/55329452/227768973-41936d91-6240-427b-934b-8f3ea2a93104.webm)

**Comment by venkat2305** [comment]
note that if videowall/card are hidden, custom button disappears. 
it's working as I wanted. thanks for adding this

**Comment by venkat2305** [comment]
https://user-images.githubusercontent.com/55329452/227772575-f96a29cb-b947-4b73-9f0e-dcd75a09420f.mp4

please check the video. this is recorded with the latest version you provided

**Comment by venkat2305** [comment]
You should add it in wiki for the new users. They might think it's a big. I've turned off video walls and cards. Ii set default card state to hide. This is enough for me.
Again, thank you so much for adding this

**Comment by venkat2305** [comment]
About the wiki, I'll surely have a look at it and see how I can improve it. I appreciate your effort and attention. Again, many thanks.
