### ISSUE TITLE
[Feature] Auto-pause background videos

### ISSUE THREAD

**Issue by venkat2305** [raingart/Nova-YouTube-extension#73]
**Feature request: Auto-pause background videos**

**Description:** I'm watching a video and opened multiple videos in a new tab (using scroll wheel button). when I opened the new video, the new video starts playing pausing the original video (which I wanted to listen). This is undesirable and inconvenient. to avoid this, it would be great to have an option which automatically pauses the videos loaded in the background. This would greatly improve the user experience.

**Comment by raingart** [comment]
i tried in edge and in my background (if you didn't activate the tab) the video never plays

Are you sure you didn't activate the tab?

**Comment by venkat2305** [comment]
it starts playing after i activated the video. but I want the original video to keep playing until I manually start playing the new videos? does it makes sense?

**Comment by raingart** [comment]
I understand what you mean. If the video is already playing then others should stop

I'll think about how to add it to this plugin. Might have to add a new one

**Comment by raingart** [comment]
[check it](https://gist.github.com/raingart/3b7f33353965383f45ec674a33098892)

To activate, you just need to enable the plugin "Autopause when switching tabs". The requested function works by default. I guess it's obvious that this is incompatible with the other option "Autoplay on tab focus".

The video just pauses. Stopping is much more difficult to implement than pausing.

**Comment by venkat2305** [comment]
the video should be paused in the background itself. when I opened the new tab, the video pauses after playing for a breif moment. this defeats the purpose of having the original video being played continuously without any interuption until we start playing a new video manually.then, the original video should pause and the new video should play.

**Comment by venkat2305** [comment]
no it seems like its paused but, it starts playing after a moment. Please check this video.


https://user-images.githubusercontent.com/55329452/226631601-9cc2ec47-6784-4e16-942b-6ce62fba9c3e.mp4

**Comment by venkat2305** [comment]
![image](https://user-images.githubusercontent.com/55329452/226671886-85f6acc0-d253-4189-b6c1-b114d41fa4b8.png)

this pic is from the settings page of enhancer for YouTube. I'm asking for the features which are checked. In case my explanation above was not adequate or clear, this img should clarify it better.

**Comment by venkat2305** [comment]
its working. 
so many extensions, If this can be added to nova that would be great. if not, I would enable that extension for this one purpose only, devoting more ram in the process.
btw, in this latest version hide buttons is not working. have you changed anything. 

settings : 
{"channel-default-tab":"on","channel-trailer-stop-preload":"on","channel_default_tab":"videos","details-buttons":"on","details_buttons_hide":["share","clip","download","thanks"],"disable-video-cards":"on","lang_code":"en","livechat-visibility":"on","livechat_visibility_mode":"hide","metadata-hide":"on","mix_disable":"on","pause-background-tab":"on","player-disable-fullscreen-scroll":"on","player-hide-elements":"on","player-pin-scroll":"on","player_float_scroll_position":"top-right","player_float_scroll_size_ratio":"1.9","player_hide_elements":["videowall_endscreen","card_endscreen","autonav_toggle_button","size_button","miniplayer_button"],"playlist-collapse":"on","playlist-duration":"on","playlist-reverse":"on","playlist_duration_progress_type":false,"redirect-disable":"on","related-visibility":"on","related_visibility_mode":"hide","report_issues":"on","scroll-to-top":"on","scroll_to_top_smooth":"on","scrollbar-hide":"on","search_query_date":false,"search_query_sort":false,"shorts-redirect":"on","sidebar-channel-links-patch":"on","subtitle-style":"on","subtitle_bold":"on","subtitle_selectable":"on","thumbs-hide":"on","user-api-key":"","video-autopause":"on","video-quality":"on","video-unblock-region":"on","video-unblock-warn-content":"on","video_autopause_embed":"on","video_quality":"hd1080","video_unblock_region_domain":"piped.video"}

**Comment by raingart** [comment]
>btw, in this latest version hide buttons is not working. have you changed anything.

Probably not. Unless you are using a browser version lower than 105. then the buttons in the description will not hide

And what buttons - player or descriptions? what's in the console? when lazy loading from another page. It seems to work for me

By the way, I managed to debug the extension code that you provided. I found out the startup code section. I'm not sure if I'll be using his play-blocking method.
The author uses the substitution of the built-in video.play function, which is quite dangerous. Complete interception of playback can break the player. It also requires implementation before launching the video. For if you fail, you can break the player

![Screenshot_1](https://user-images.githubusercontent.com/13064767/227901496-8a2c7bb9-4680-4f0c-ace4-be0650146ab1.png)

**Comment by venkat2305** [comment]
![image](https://user-images.githubusercontent.com/55329452/227904481-d0ccef8c-de33-4ff9-877a-4d432dcd8a54.png)
![image](https://user-images.githubusercontent.com/55329452/227904573-7d6d89bf-55e3-4b06-912d-6a8d845d8118.png)
![image](https://user-images.githubusercontent.com/55329452/227904637-8554a388-8207-4244-9cb0-78c3c03b4bb9.png)

**Comment by raingart** [comment]
@venkat2305 Finally I got a positive result.
It took a lot of time to bypass the delay when playing/pausing.
But finally I was able to get rid of it.

**Comment by raingart** [comment]
Hi @venkat2305
I changed the behavior in the latest ver.
To select what you requested earlier, switch "Autoplay on tab focus" on "always for not started"
