### ISSUE TITLE
[Bug] scroll to top button is missing in the settings

### ISSUE THREAD

**Issue by venkat2305** [raingart/Nova-YouTube-extension#74]
*Describe the bug*

![image](https://user-images.githubusercontent.com/55329452/226467770-d6d3383e-f3ea-4ba7-876c-5373ec4656fd.png)

scroll to top button is missing in the nova settings(im on the latest script which you provided before)

 - Browser: Chrome 999.0 
 - ...monkey 99.1 
 - Nova 6.6.1

**Comment by venkat2305** [comment]
![image](https://user-images.githubusercontent.com/55329452/226469145-8cc15b21-0475-46d0-8cbb-1bee8d6b32f7.png)

scroll to top is not present in the script you provided

**Comment by raingart** [comment]
what does the browser console display?

Maybe something is blocking the display

**Comment by venkat2305** [comment]
![image](https://user-images.githubusercontent.com/55329452/226470370-b6304c5e-c35a-45ff-ada0-00947adf3472.png)

![screencapture-raingart-github-io-options-html-2023-03-21-03_00_03](https://user-images.githubusercontent.com/55329452/226470396-9faa1e1e-96c8-469e-bc5d-5210ce561ca1.png)

**Comment by venkat2305** [comment]
its simply no there. don't know what's wrong

**Comment by raingart** [comment]
need console output
with blocking or file inaccessibility errors

![Screenshot_8](https://user-images.githubusercontent.com/13064767/226470699-5ee115e7-f30c-4641-934b-7227e00e2544.png)

**Comment by venkat2305** [comment]
![image](https://user-images.githubusercontent.com/55329452/226471331-cc931670-9bbf-4398-ac30-7ed94111d670.png)

**Comment by raingart** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/13064767/226471708-7d8bfde6-f20f-467f-b9ec-13b3f285521d.png)

pay attention to the 2nd line in the screenshot -ublock blocked. Apparently one of your block lists has a mention of disabling the scroll up buttons.
Of course, I can prename for a bypass. But these are private issues. You as a user must be aware of what you are activating.

**Comment by venkat2305** [comment]
I turned off ublock for the settings page and its fixed now. Thanks for the help
