### ISSUE TITLE
[Feature] playlist duration improvement

### ISSUE THREAD

**Issue by venkat2305** [raingart/Nova-YouTube-extension#75]
can you add the playlist duration data here as well? some where along those markings
![image](https://user-images.githubusercontent.com/55329452/226471210-84d708aa-c769-4639-bdaa-8745f6b3790d.png)

**Comment by raingart** [comment]
youtube has redesigned page. And the plugin cannot find where to insert the information.
I do not use all plugins and constantly test. Therefore, part of the functionality is not in my field of vision.
I'll try to fix it now

**Comment by venkat2305** [comment]
By the way, are you planning to publish nova on the chrome webstore?

**Comment by venkat2305** [comment]
this is so sad. I just found out about nova and I am loving this script.

**Comment by venkat2305** [comment]
never thought , i could style yt subs like netflix. 
![image](https://user-images.githubusercontent.com/55329452/226476058-2f584595-b2c1-4000-890c-b76fe9a04797.png)

**Comment by venkat2305** [comment]
they are not good.

**Comment by venkat2305** [comment]
its fixed. Thanks
