### ISSUE TITLE
[Feature] remove buttons on the player

### ISSUE THREAD

**Issue by venkat2305** [raingart/Nova-YouTube-extension#76]
I would like to request an option to remove the buttons on the player that I don’t use, such as auto play, mini player and cinematic mode. I've never used these buttons. These buttons clutter the player interface and interfere with the video chapters. Removing them would make the player more streamlined and user-friendly.

**Comment by venkat2305** [comment]
Please do share it.

**Comment by venkat2305** [comment]
hide option cinematic mode is needed. and I found this crazy bug. clicking setting button on the player is changing autoplay setting. check this video.
[(3) Rit jealous moment - YouTube.webm](https://user-images.githubusercontent.com/55329452/227370571-ee623a64-203e-426f-bd82-02703cc2c578.webm)

**Comment by venkat2305** [comment]
can you change auto nav toggle to autoplay toggle. I was confused

**Comment by raingart** [comment]
> hide option cinematic mode is needed. and I found this crazy bug. clicking setting button on the player is changing autoplay 

I have no such error. Possible conflict with another script

**Comment by venkat2305** [comment]
i meant this option. 
![image](https://user-images.githubusercontent.com/55329452/227445775-01bf7049-9599-4f67-b16e-2cc5662ebed6.png)
there is no option to hide that element.

**Comment by venkat2305** [comment]
its fine and looks clean as well

**Comment by raingart** [comment]
Has that crazy bug appeared yet?

because I didn't understand where it could come from. Probably a conflict with another script

[nova-extensions_v1.39.1.zip](https://github.com/raingart/Nova-YouTube-extension/files/11060788/nova-extensions_v1.39.1.zip)

**Comment by venkat2305** [comment]
[How Scammers Destroyed an Entire Country - YouTube.webm](https://user-images.githubusercontent.com/55329452/227500718-1cf13799-284e-40bb-bfa4-f59d439f2915.webm)

i chose to hide the autoplay toggle. but the bug still exists.

**Comment by raingart** [comment]
final the plugin

![Screenshot from 2023-03-24 14-41-52](https://user-images.githubusercontent.com/13064767/227526426-16b33426-d028-404a-8fb5-8858efe57b49.png)
