### ISSUE TITLE
[Feature] geoblock bypass

### ISSUE THREAD

**Issue by venkat2305** [raingart/Nova-YouTube-extension#77]
the present solution to bypassing Geo block is ineffective. I have an idea for how to fix the problem with the current implementation. There are some piped instances that can access videos that are blocked in certain regions. For example, kavin.rocks libre (Official) instance works for me. I suggest that when a video is blocked for a user, it should either automatically switch to a piped instance that can play it or offer a button to do so manually. Additionally, please investigate how this solution can be implemented for embedded videos that are also blocked. Can you look into how this can be done?
please have a look at this script [Youtube 2 Piped](https://greasyfork.org/en/scripts/457203-youtube-2-piped)
Thanks.
[this](https://www.youtube.com/watch?v=6pX93dXfH9s) is geoblocked for me and I was able to watch in piped with the above-mentioned instance.

**Comment by raingart** [comment]
In the release that is being developed, there is a drop-down list (with the ability to specify your url) with a choice of mirrors
I only know 2.

It also opens a map with a list of blocked regions. Might be worth opening the map optionally
example https://watannetwork.com/tools/blocked/#url=6pX93dXfH9s

about the piped.video domain, I forgot that they can be used as a mirror
I need to try other youtube mirrors, like invidious

But it didn't work in my test videos. And in your strange error about the format mismatch issued
https://invidious.snopyta.org/watch?v=6pX93dXfH9s

**Comment by venkat2305** [comment]
Can you share a video showing how it works if it's development is done?

**Comment by venkat2305** [comment]
> with a choice of mirrors. I only know 2.

**Comment by venkat2305** [comment]
Thanks. piped instance is working. 

> it is clear that not everyone will understand the principles of work.

yes. even if there is a detailed guide, people would still get confused. but not everyone uses it, and those who will want use it, they can come to github issues and accordingly, wiki should be updated.

**Comment by venkat2305** [comment]
is it implemented for embeded videos? for [reference](https://anilist.co/anime/136430/VINLAND-SAGA-SEASON-2/)

**Comment by venkat2305** [comment]
for embeded videos, it is asking to disable pop up blocking. is there a better way to implement this. allowing popups for a site would be annoying.

**Comment by raingart** [comment]
The problem is that in embed there is no indication that the video is not available due to regional restrictions. Just a mistake. And there is a high probability that the cause of the error may be different. And how to find out whether to run a redirect or not?

**Comment by raingart** [comment]
Disable embed support for this plugin

**Comment by venkat2305** [comment]
Can you elaborate? Is it not easier to maintain a single version?

**Comment by venkat2305** [comment]
here's my take: I use many open-source apps, but I'm involved with only a  few projects. I'm benefitting from the contributions of somebody else. the same way, somebody else is benefitting when I'm contributing. extending this, I would say everyone should get benefits. that's just my opinion. feel free to do what you wish.
