### ISSUE TITLE
Autoplay/pause doesnt work when switching from one yt tab to another, just thoutht you should know

### ISSUE THREAD

**Issue by zkisaboss** [raingart/Nova-YouTube-extension#78]
0.39.0 | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

**Comment by raingart** [comment]
Added exception in incognito mode in beta version

```
Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.get (<anonymous>:78:470)
```

The reason was this option:

![Screenshot from 2023-03-25 10-28-47](https://user-images.githubusercontent.com/13064767/227706398-6025e447-1971-4c54-89f3-ee48844a2e04.png)

**Comment by raingart** [comment]
I sent you a link to the beta in another issue. Maybe it works there. But most likely not

Perhaps users misunderstand its option. This option allows you to play only one instance of the video. If the script detects that video playback has started in another tab, it stops playback.

One user requested (#73) the ability to disable playback if a video in another tab is already running. At the moment this is not implemented.

**Comment by zkisaboss** [comment]
I'll close the issue then, thanks

**Comment by raingart** [comment]
Hi @zkisaboss 
The behavior of the plugin "Autopause when switching tabs" has changed in the latest ver
You may need to change the "Autoplay on tab focus" setting
