### ISSUE TITLE
[Bug] Corrupted on Firefox Nightly

### ISSUE THREAD

**Issue by Koishukaze** [raingart/Nova-YouTube-extension#83]
Latest version of Nova says its corrupted on firefox

 - Browser: Firefox Nightly V 114.0a1

**Comment by raingart** [comment]
The instructions are not accurate. The `manifest.json` file must be at the root of the archive. And if you download `Nova-YouTube-extension-master.zip` then it will be inside the directory. You need to move all files (the directory) to the root of the archive
