### ISSUE TITLE
 [Bug] Add sort/filter to "Save to playlist" menu doesn’t work

### ISSUE THREAD

**Issue by Fred-Vatin** [raingart/Nova-YouTube-extension#85]
This function doesn’t work anymore in Nova. I use *Youtube Save to... playlist incremental search* as an alternative that still works.

# SETUP
 - Browser: Firefox 112.01
 - Tampermonkey 4.18.1
 - Nova 0.40.0

**Comment by Fred-Vatin** [comment]
Not better.

**Comment by Fred-Vatin** [comment]
![image](https://user-images.githubusercontent.com/22337329/234995724-488a939b-ca7e-43db-95e1-4f0929de40d5.png)

**Comment by Fred-Vatin** [comment]
Same

**Comment by Fred-Vatin** [comment]
It seems to work when I click **save to playlist** from any items in my **watch later playlist** that is currently playing or any video that is currently playing.

But if I go to the home page (https://www.youtube.com/) or my subscriptions or else and click **save to playlist** on any video, I have no filter
![image](https://user-images.githubusercontent.com/22337329/235014965-37ebca1b-c657-4f5c-8ed1-da1881976fd7.png)

I tried to disable uBlock origin to no avail.

No errors or warnings in console related to nova.

debug from nova
```
Object { "video-quality": "on", video_quality: "hd1080", "player-float-progress-bar": "on", player_float_progress_bar_height: "3", player_float_progress_bar_opacity: "0.65", "player-quick-buttons": "on", player_buttons_custom_items: (4) […], player_buttons_custom_popup_width: "2.5", player_buttons_custom_hotkey_toggle_speed: "a", "video-unblock-region": "on", … }
​
"channel-default-tab": "on"
​
channel_default_tab: "videos"
​
lang_code: "en"
​
"player-float-progress-bar": "on"
​
"player-quick-buttons": "on"
​
"player-resume-playback": "on"
​
player_buttons_custom_hotkey_toggle_speed: "a"
​
player_buttons_custom_items: Array(4) [ "quick-quality", "toggle-speed", "popup", … ]
​
player_buttons_custom_popup_width: "2.5"
​
player_float_progress_bar_height: "3"
​
player_float_progress_bar_opacity: "0.65"
​
player_resume_playback_url_mark: "on"
​
"playlist-duration": "on"
​
playlist_duration_percentage: "on"
​
playlist_duration_progress_type: false
​
report_issues: "on"
​
"save-to-playlist": "on"
​
"shorts-redirect": "on"
​
shorts_disable: "on"
​
shorts_disable_min_duration: "0"
​
"square-avatars": "on"
​
"thumbs-hide": "on"
​
"user-api-key": ""
​
"video-quality": "on"
​
"video-unblock-region": "on"
​
video_quality: "hd1080"
​
video_unblock_region_domain: "hooktube.com"
​
video_unblock_region_open_map: "on"
```
 ## Plugins status
![image](https://user-images.githubusercontent.com/22337329/235015826-713f5572-d818-4dd8-9672-d0c04805d584.png)
![image](https://user-images.githubusercontent.com/22337329/235015849-9c47bc0c-6613-4573-bef3-57a596f17b83.png)
![image](https://user-images.githubusercontent.com/22337329/235015872-a287c670-1e58-42ec-ba5a-9bb0277ce1d0.png)

**Comment by raingart** [comment]
>But if I go to the home page (https://www.youtube.com/) or my subscriptions or else and click save to playlist on any video, I have no filter

I never visit the main page, and therefore I didn’t know that this option can be called from there. 

This page was not on the allowed list. I do not use all implemented features. And that's why a lot of things remain out of my field of vision. You can send a list on which other pages this option is available (except for "home" and "watch"), isn't there in embed page?


![Screenshot from 2023-04-28 11-26-35](https://user-images.githubusercontent.com/13064767/235096126-04c5529f-1f76-42c6-a98c-ab374481c565.png)

**Comment by Fred-Vatin** [comment]
It needs this settings to work everywhere :
```js
run_on_pages: 'home, watch, feed, channel, results, -mobile',
```

**Comment by raingart** [comment]
ok, I will add these changes to the next release
