### ISSUE TITLE
[Feature] add Return YouTube Dislike

### ISSUE THREAD

**Issue by big-cat-loaf** [raingart/Nova-YouTube-extension#89]
Add that you can show the Youtube Dislike with you client. 
Main Website:  https://www.returnyoutubedislike.com
API is accessible: https://www.returnyoutubedislike.com/docs 
Endpoints: https://returnyoutubedislikeapi.com/swagger/index.html
Usage Rights: https://www.returnyoutubedislike.com/docs/usage-rights

**Comment by raingart** [comment]
I don't understand why do this? their implementation is very "clean". especially the userscipt version.
I also looked at the version of the extension. It's a little more complex, but more functional.
I won't do anything new. Just an alternative truncated implementation?

https://www.returnyoutubedislike.com/install


I can do something like this:
- https://greasyfork.org/en/scripts/436254-returninvidiousdislike/code
- https://greasyfork.org/en/scripts/461909-invidious-dislike-counter/code
- https://greasyfork.org/en/scripts/459201-return-youtube-dislike-for-invidious/code

just display the number of dislikes. Do you want that?

**Comment by big-cat-loaf** [comment]
I thought of the extension like an all in one package that replace the most of the best addon to Youtube like you did with SponsorBlock or Youtube Playback Speed Control. That why I suggesd it and yes I do want just the dislkies nothing complicate.

**Comment by big-cat-loaf** [comment]
Please only work on this when you have free time this feature was only ment to be a thing of the lowest priority and not something big. When your that busy you can close this issue request anytime.
thank you

**Comment by raingart** [comment]
[check beta](https://gist.github.com/raingart/c024f4ab67bf3de18a560ebb22b85c32/raw/03371a4c7486c1cc0e3066cead61881debd28730/nova-test.user.js)

![Screenshot from 2023-06-26 13-38-21](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/614b193e-3a14-434d-982c-4fd5903a14c6)

**Comment by big-cat-loaf** [comment]
link doesn't work,
![image](https://github.com/raingart/Nova-YouTube-extension/assets/100969549/a9c13a72-f1d4-499c-9f1c-4621e1737303)
It in German sorry but The beta did work before and even then it did't display any dislikes.

**Comment by big-cat-loaf** [comment]
translation: 
The site is unavailable. 
The webpage at may be temporarily unavailable or may have been permanently moved to a new web address.

**Comment by big-cat-loaf** [comment]
Youtube Dislike doesn't work 
error code 
[www.youtube.com-1687792487578.log](https://github.com/raingart/Nova-YouTube-extension/files/11870906/www.youtube.com-1687792487578.log)

**Comment by big-cat-loaf** [comment]
New Error code 
still doesn't work 
[www.youtube.com-1687794553824.log](https://github.com/raingart/Nova-YouTube-extension/files/11871220/www.youtube.com-1687794553824.log)

**Comment by big-cat-loaf** [comment]
yes it does work!!!

**Comment by big-cat-loaf** [comment]
oh no.... 
new bug

**Comment by big-cat-loaf** [comment]
Just found

**Comment by big-cat-loaf** [comment]
https://github.com/raingart/Nova-YouTube-extension/assets/100969549/2b36fb32-d59d-426d-956d-2701bd831493

**Comment by big-cat-loaf** [comment]
its replacing the dislikes. Like why Youtube?????

**Comment by big-cat-loaf** [comment]
I did a bit of testing a found out is only accoured when you go back the other thing like clicking on a new Video is my fault sorry but he bug still exist.

**Comment by raingart** [comment]
dude, you have no idea how the "go back" button works in a browser.
In short, the browser returns part of the page from the cache. But neither YouTube nor Nova know what happened. If something breaks, that's how it's meant to be. And if something continues to work, this is a miracle, if not an error.
Especially if a webhook or web socket is used. Almost all interactive pages break.

**Comment by raingart** [comment]
I'm answering the [other guy at the same time](https://github.com/raingart/Nova-YouTube-extension/issues/91#issuecomment-1607952763).
and if it is short that at transition. Especially from the cache. Nova cannot be reconfigured correctly. Nova sometimes breaks during a transition, and when I return, I can’t even imagine what restarts and what remains. Most likely that everything except a complete restart of the plugins does not work.

**Comment by raingart** [comment]
I will close this topic. That's why I recommended using the official script and not my implementation. 
I think you already regret that you suggested that I write this plugin. Because what could break broke. And what works, works because it hasn't broken yet.

**Comment by big-cat-loaf** [comment]
Ok I will close it. We all agree that it work so, It work.

**Comment by big-cat-loaf** [comment]
What heppend?
