### ISSUE TITLE
[Suggestion] Please Add fullscreen windowed player

### ISSUE THREAD

**Issue by ShojiVR** [raingart/Nova-YouTube-extension#9]
It will be great to add this feature since it is more faster than using actual full screen

**Comment by raingart** [comment]
Perhaps you will be satisfied with this script:
https://openuserjs.org/scripts/Zren/Resize_YT_To_Window_Size

**Comment by ShojiVR** [comment]
yes this is what im looking for, i hope this will be integrated to nova youtube someday

**Comment by raingart** [comment]
![Screenshot from 2022-04-29 13-05-57](https://user-images.githubusercontent.com/13064767/165925895-4f04ffbd-6c3f-4a51-b22d-36a33a79834e.png)

Added new options to the plugin "Player full-with mode" (theater-mode)

try new ver: https://openuserjs.org/scripts/raingart/Nova_YouTube
or from the repository if you use the extension

**Comment by ShojiVR** [comment]
I have turned on the full with mode but it still not working

i dont want to turn on cinema mode since i want the background remain visible.

and thanks for watching my video.

**Comment by raingart** [comment]
Built-in "theater-mode" by default stretches the video to full width
The plugin "Player full-with mode" essentially calls a built-in function including "theater-mode"

The [Resize YT To Window Size](https://openuserjs.org/scripts/Zren/Resize_YT_To_Window_Size) script mentioned above also stretches the video vertically. But it all depends on the aspect ratio of the video.
In my monitor, the video almost always rests on the width. And the scripts just stretched the player.

There is a video with square aspect ratio
I use for testing
// testing wide-screen video
// https://www.youtube.com/watch?v=B4yuZhKRW1c
// https://www.youtube.com/watch?v=zEk3A1fA0gc

// for testing square-screen
// https://www.youtube.com/watch?v=v-YQUCP-J8s
// https://www.youtube.com/watch?v=yFsmUBLn8O0

I tried to write a function that turned on the full screen when the video was loaded. But it works with a delay.
I have attached the extension archive.
[nova-extensions_v1.26.0.zip](https://github.com/raingart/Nova-YouTube-extension/files/8590990/nova-extensions_v1.26.0.zip)

I don't fully understand what you want. Full screen or stretch to viewport

**Comment by raingart** [comment]
Add new plugins
- Player full-with mode > Full-viewport mode
- Fullscreen player mode

Hope it helps, I can't offer better
