### ISSUE TITLE
[Bug] Theatre Mode doesn't work

### ISSUE THREAD

**Issue by Nuttar** [raingart/Nova-YouTube-extension#92]
Using Tampermonkey in both Brave and Firefox.

Theatre Mode doesn't seem to work, and also prevents scrolling entirely. I was using a script which only resized theatre mode to the full browser viewport, and then it broke entirely about an hour or so ago. So I ended up finding this script when looking for a fix. Though Nova's Theatre Mode is much less broken in comparison.

Also wondering if it were working as intended, does the full-viewport option allow scrolling down the page while the video stays the same size? and if scrolling to the top, will the Header be there making it hard to get it aligned properly again? if not, could that be an option? The previous script just moved the Header below the video instead, which worked great for me.

**Comment by Nuttar** [comment]
I see, I suppose what i'm asking for isn't as simple as just the Theater mode like those 2 alts; but like an extension of it. I specifically used this before it broke a few hours ago. https://github.com/Zren/ResizeYoutubePlayerToWindowSize
It now has a viewport-sized blank area above the player, and the text under the player like channel name, part of the description, etc. overlaps the bottom of the video area.

Regardless of whether you can fix it or not before another alternative eventually pops up, thanks for your efforts. I assume I'd be able to use Novas' other features with a similar script for a video fill as long as Novas' Theater plugin is disabled.

**Comment by Nuttar** [comment]
Looks like Zren has fixed their script #https://github.com/Zren/ResizeYoutubePlayerToWindowSize/issues/77#issuecomment-1612224069

I tried the CSS edit in StyleBot with the broken script enabled and it looks good. I don't know if you're interested in the script for proper integration, but I don't mind using both at once if they'll keep working well together.

**Comment by raingart** [comment]
found a problem. It turns out that YouTube changed the name of the elements inside and the plugin did not work at all
to make it work, you need to replace the line
`PLAYER_CONTAINER_SELECTOR = 'ytd-watch-flexy[theater]:not([fullscreen]) #player-theater-container',`
on
`PLAYER_CONTAINER_SELECTOR = 'ytd-watch-flexy[theater]:not([fullscreen]) #player-container'`

also omitted ` break;` before `case 'smart':` line
Turns out the plugin (Theater mode > Mode > full-viewport) was not working.

**Comment by raingart** [comment]
>Header be there making... 

it's only available when you select `Mode > cinema`. it becomes visible on hover

Sorry for not replying right away. Since I needed to understand how the plugin works, why it doesn't work now. And remember what he does. I don't use it and forgot

If I'm not mistaken, I once came across a script that seemed to do what you want. Ie there, on a key call, a search bar appeared and it seemed like you could scroll the page. If I find it I will send a link.

**Comment by raingart** [comment]
found it
https://greasyfork.org/en/scripts/442089-pkga-youtube-theater-mode

**Comment by raingart** [comment]
I found another cool script

https://greasyfork.org/en/scripts/436667-better-youtube-theatre-mode

**Comment by Nuttar** [comment]
I like pkga's layout with chat, but it seems broken still. With Zren's updated Resize script working, i'll be using that for now.
I guess i'll leave closing this upto you if/when you get to fixing up Novas theatre mode. Thanks for the help.

**Comment by raingart** [comment]
added new parameter `offset` - [adaptation of this script](https://greasyfork.org/en/scripts/436667-better-youtube-theatre-mode)

also added appearance of serchbar on hover (to `full-viewport`)

https://gist.github.com/raingart/2bb7d6e513a2827109e2de20e7eb9e26/raw/b05c0c098ce4df78d2c2646009ce12859f84c8bf/nova.user.js

if you test and there is no gap then I will close this issue

**Comment by Nuttar** [comment]
Scrolling the page doesn't work, even when toggling out of Theater. Changing [Hide scrollbar in watch page] doesn't seem to help (or in this case, changes nothing), and I have no other Tampermonkey scripts active.

**Comment by raingart** [comment]
Have you tried hovering your mouse over the player control panel from the bottom and scrolling over it?

**Comment by Nuttar** [comment]
Ah, I see. Unfortunately it only scrolls down once, and then scrolling up or down stops working.

**Comment by Nuttar** [comment]
My exported settings:

`{"player-hide-elements":"on","player_hide_elements":["videowall_endscreen","card_endscreen","prev_button","next_button","miniplayer_button","logo_button"],"disable-player-sleep-mode":"on","theater-mode":"on","player_full_viewport_mode":"force","player-live-duration":"on","video-unblock-warn-content":"on","player-quick-buttons":"on","player_buttons_custom_items":"thumbnail","video-unblock-region":"on","video_unblock_region_domain":"yewtu.be","video-quality":"on","video_quality":"hd1440","video_quality_manual_save_in_tab":"on","disable-video-cards":"on","thumbs-shorts-duration":"on","miniplayer-disable":"on","channel-trailer-stop-preload":"on","shorts-redirect":"on","channel-default-tab":"on","channel_default_tab":"videos","related-visibility":"on","related_visibility_mode":"hide","redirect-disable":"on","search_query_sort":false,"search_query_date":false,"user-api-key":"","lang_code":"en"}`

Also, I can't view the google link without logging in. I don't have a google account. I'm using Brave browser: [Version 1.52.126 Chromium: 114.0.5735.133]

**Comment by raingart** [comment]
I have been emailed several times by different users of Brave and Edge
and they had errors that I didn't have on pure Chromium
I believe that the changes in these browers are significant. I'll try to check sometime in brave how everything works.
Most likely this is a bug specific to Brave.

**Comment by Nuttar** [comment]
Gotcha. Here's a recording anyway. I'm rapidly scrolling most of the time.
https://github.com/raingart/Nova-YouTube-extension/assets/94299/613f9c17-f2b6-4da9-babf-1c1b00332287

**Comment by Nuttar** [comment]
I don't notice any errors in console related to Nova.
Just years of preference of layout/extensions from chrome into brave. I do use firefox too but not for general browsing which includes youtube usage. I think Brave did insert affiliate links, but quickly took it out, as far as i know.

**Comment by raingart** [comment]
Found the error reason. CSS hiding the scrollbar:

```
/* Hide scrollbars */
body { overflow: hidden; }
```

https://gist.github.com/raingart/2bb7d6e513a2827109e2de20e7eb9e26/raw/f00ee75de8ad900bfe4c454e19cb74639c2d8512/nova.user.js
