### ISSUE TITLE
[Bug] Expand Description Bugged

### ISSUE THREAD

**Issue by alkaris2** [raingart/Nova-YouTube-extension#93]
## Describe the bug

This toggle option for Expand Description is bugged, it'll always auto-expand the description of videos when it's not even toggled on, or if set to `on hover`, I've tested this out in Vivaldi and Firefox and both have the exact same behaviour regardless what it's set on.

 
- Vivaldi 6.0.2979.25 (Stable channel) stable (64-bit) / Firefox114.0 (64-bit)
 - Violentmonkey - v2.14.2
 - Nova - 0.43.0

**Comment by raingart** [comment]
rewrote the plugin. Now everything should work.
You can check in [beta](https://gist.github.com/raingart/3c05540b49f2dd9272bb68333bc35c64/raw/2b3f04611a35f289f4e82449a017e12d69265bd5/nova-beta.user.js)

**Comment by alkaris2** [comment]
This bug seems to still be present, expand description still auto-expands on load when it hasn't been enabled or when it's set to either On Hover or Always. As GreaseMonkey script I tested multiple times, if I disabled in the menu of GreaseMonkey the issues goes away, enabling it again the issue comes back.

If Disabled it should be like this;

```HTML
<tp-yt-paper-button id="collapse" class="button style-scope ytd-text-inline-expander" style-target="host" role="button" tabindex="0" animated="" elevation="0" aria-disabled="false" hidden=""><!--css-build:shady-->Show less<paper-ripple class="style-scope tp-yt-paper-button"><!--css-build:shady-->
    

    <div id="background" class="style-scope paper-ripple" style="opacity: 0;"></div>
    <div id="waves" class="style-scope paper-ripple"></div>
</paper-ripple></tp-yt-paper-button>
```

if Enabled it looks like this

```HTML
<tp-yt-paper-button id="collapse" class="button style-scope ytd-text-inline-expander" style-target="host" role="button" tabindex="0" animated="" elevation="0" aria-disabled="false"><!--css-build:shady-->Show less<paper-ripple class="style-scope tp-yt-paper-button"><!--css-build:shady-->
    

    <div id="background" class="style-scope paper-ripple" style="opacity: 0;"></div>
    <div id="waves" class="style-scope paper-ripple"></div>
</paper-ripple></tp-yt-paper-button>
```

Another section shows for `is-expanded` if the Show More has been clicked to expand the description, and it removes `is-expanded` when its not showing full description after clicking Show Less.

```html
<ytd-text-inline-expander id="description-inline-expander" always-show-expand-button="" class="style-scope ytd-watch-metadata" is-expanded="">
```

your script isn't respecting the default state when it's not enabled, or set to the other options, it just auto-expands it anyway regardless of what's enabled or not.

**Comment by raingart** [comment]
GreaseMonkey unsupported.

more info #81

there is an [experimental ver](https://gist.github.com/raingart/87cdad75f8e11f21f6ee937eab4e6962) or use [scriptcat](https://github.com/scriptscat/scriptcat) it supports GreaseMonkey/Violentmonkey  scripts

**Comment by raingart** [comment]
I see no problems with [plugin code](https://github.com/raingart/Nova-YouTube-extension/blob/master/plugins/details/description-expand.js#L27-L38) there are 10 lines of code.
Probably a problem with your Monkey Or browser. I periodically sing the gaps of users of different forks of chromium that something is not working for them. I use and test only in the original version of Chromium stable + VioletMonkey.
there may also be a conflict with other plugins.

- Try extension version.
- Try to create another user in the browser and test without other scripts and extensions that affect youtube
also disable other plugins. If the error repeats, then specify specific versions (Browser, Monkey, Nova) so that I can reproduce these errors.

**Comment by raingart** [comment]
I just found out that in the plugin "Float player progress bar" there is a function for auto-expanding the description.
