### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by MarkSpizu** [raingart/Nova-YouTube-extension#94]
Youtube pop-up appears

_Your browser does not support css ":has()" operator.
Approximately 5% of opportunities will be unavailable_

Firefox, Violentmonkey.

Reverted back to [v0.43.0] no pop-up.

**Comment by raingart** [comment]
1. click "ok" this should hide the popup.
2. Or update your browser
3. Or you can delete the line that is responsible for the popup( line 58-62)

**Comment by raingart** [comment]
one hundred clones of chromium support this operator. Firefox doesn't. Well I could do a workaround via js. But why do I need it? if i can do it through `:has()`
For example the plugin `Buttons > Hide items`  relies entirely on this operator

![image](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/32abd785-586e-4c30-9e77-a556a4e6d138)

**Comment by MarkSpizu** [comment]
I deleted (line 58-62). no pop-up.

Anyway, the previous version [v0.43.0] was working fine. I didn't see a change log, I don't know if it was something important to be worth updating to [v0.43.1].

Thanks!

**Comment by raingart** [comment]
changelog https://github.com/raingart/Nova-YouTube-extension/releases/tag/v0.43.1

**Comment by MarkSpizu** [comment]
Good to know. Maybe in the next version you will find a way to make the script work in Firefox too. If not, I will keep deleting those lines. 

Thanks!

**Comment by raingart** [comment]
don't you just have to click on the ok window:


![Screenshot_8](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/6ce9abeb-f9fb-4ba9-a336-a0188574b5cb)

and the message should no longer appear. It should store the state in localstorage:

![Screenshot_1](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/594322fd-7b52-4194-9114-90c20a81e409)

I was reinsured in advance and decided to warn the user in such ways that part of the functionality will not work.

It may be worth hiding this warning as before. It seemed to me that 1 time to notify the user would be better than not saying anything

As I understand correctly, you do not save, and the notification appears constantly? You may be in incognito mode

**Comment by MarkSpizu** [comment]
Yes, is saved after OK. Normal mode. I don't use Private/Incognito. It's just that sometimes it appears again, I don't know what the reason is.

Could you do "hide warnings" in Options - OTHER?

**Comment by raingart** [comment]
I added an exception for embedded videos. Please check this version
https://openuserjs.org/scripts/raingart/Nova_YouTube
if the problem persists, I will remove this notification in the next release.

Also blocking cookies for the iframe can be the cause of the bug:

![Screenshot_1](https://github.com/raingart/Nova-YouTube-extension/assets/13064767/67432876-7db0-4100-8952-02284f445392)

**Comment by MarkSpizu** [comment]
No change. For cookies I use this https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies

**Comment by raingart** [comment]
then decided I'll remove the popup warning.
