### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by big-cat-loaf** [raingart/Nova-YouTube-extension#98]
[www.youtube.com-1691487133892.log](https://github.com/raingart/Nova-YouTube-extension/files/12289686/www.youtube.com-1691487133892.log)
[www.youtube.com-1691487141210.log](https://github.com/raingart/Nova-YouTube-extension/files/12289687/www.youtube.com-1691487141210.log)

 - Browser: Version 115.0.5790.110 (Official Build, ungoogled-chromium) (64-Bit)
 - Nova 0.43.3

**Comment by raingart** [comment]
Thank you.
The fix will be in the next release.

or you can now disable the faulty block by deleting the line
`expandAvailableRatesMenu();`

or install [beta ver](https://gist.github.com/raingart/d61223c939fc1b02f0f7a14aaaa8cbbd)
